Netcracker/KubeMarine

kubemarine/resources/configurations/globals.yaml
* Error preparing data for projected volume kube-api-access-gd628 for pod cloud-rbm-pg-release/rb-mf-subpath-job-10c59fa0e-bss-fmzng: object "cloud-rbm-pg-release"/"kube-root-ca.crt" not registered
* Upgrade version kubernetes on the 1.23.11
=> [PSUPCLPL-10728]Error: MountVolume.SetUp failed for volume "kube-api-access-gd628" object kube-root-ca.crt not registered

documentation/Installation.md, kubemarine/resources/configurations/defaults.yaml, kubemarine/templates/plugins/calico-v3.21.yaml.j2, kubemarine/templates/plugins/calico-v3.22.yaml.j2, kubemarine/templates/plugins/calico-v3.24.yaml.j2
* `Calico` environment variables should follow from `cluster.yaml` to `calico.yaml`
* Change `Calico` YAML template and `defaults.yaml`
Not applicable
**TestCase 1**
Check if the solution works
- Hardware: 4CPU/8GB
- Inventory: FullHA
Steps:
1. Add to `cluster.yaml` some environment variable in section `plugins.calico.env`
2. Run installation with `--tasks="deploy.plugins"`
3. Check if the variable is set in `Calico` pod description
Results:
| absent | is set |
=> [MANOPD-79810] calico environment variables forwarding support

.github/workflows/patch.yaml, .github/workflows/tests.yaml
* `.github/workflows/patch.yaml` workflow fails to push to protected branches.
Fixes #202 
* The job now checkouts the branch using PAT of NetcrackerCLPLCI user which has grants to push to protected branches
**TestCase 1**
Steps:
1. Publish release that has one or more [patches](https://github.com/Netcracker/KubeMarine/blob/main/documentation/Maintenance.md#patch-identifiers).
Results:
| `Manage Patches` workflow fails | `Manage Patches` workflow deletes all patches  |
=> MANOPD-78236 Fixed patch autodeletion workflow

documentation/internal/Patches.md, kubemarine/patches/__init__.py, kubemarine/patches/p1_upgrade_calico_version.py
During release 0.7.0 we upgrade recommended calico version for kubernetes clusters 1.22.X, 1.23.X and 1.24.X.
For this reason we should add special migration action for automatic update from kubemarine 0.6.0 to 0.7.0.
Special patch was added. This patch upgrade calico version to 3.24.1 for clusters with version 1.22.X, 1.23.X and 1.24.X.
* [Install task/s with calico version 3.22](documentation/Installation.md#installation-tasks-description)
* [Migrate kubemarine](documentation/Maintenance.md#kubemarine-migration-procedure)
=> [MANOPD-000] - add upgrade calico patch

kubemarine/procedures/check_paas.py, kubemarine/resources/configurations/defaults.yaml
In 0.7.1 check_paas procedure starts failing on the 224 check (Calico configfuration check).
New approach to calico envs definition is introduced in v0.7.1. According to that an env can look like
```
NODENAME:
fieldRef:
fieldPath: spec.nodeName
```
which doesn't fit to the condition https://github.com/Netcracker/KubeMarine/blob/dcc7040664fad54cbfcf2e8dacbb8abe996f3bf1/kubemarine/procedures/check_paas.py#L1058
```
if not str(cluster.inventory["plugins"]["calico"]["env"].get(env["name"])) == env["value"]:
```
Run check_paas procedure. The check 224 should run with "valid" result.
=> Fix calico paas check

kubemarine/core/cluster.py, kubemarine/core/utils.py
Job fails if remove **shutdowned** node using maintenance procedure for **miniHA** scheme. When preserving of the information about the procedure the actual number of nodes is not taken into account.
Additionally, use the **get_final_nodes()** function to get the actual list of nodes.
none
**TestCase 1**
miniHA cluster of 3 master nodes
Steps:
1. Shutdown master node
2. Remove node from cluster using maintenance procedure
3. The node removal procedure will be fully executed, but the job will fail at the final stage of generating logs about the performed procedure. 
Results:
| Job successfully finished | Job failure with python traceback error |
=> MANOPD-76951 Fix "remote_node" procedure for miniHA

kubemarine/core/defaults.py
If use cluster_finalized.yaml as a source inventory file and run `add_node` procedure, then it is always necessary to specify `keyfile` in new node inventory because `node_defaults` section is absent.
Do not remove [node_defaults](https://github.com/Netcracker/KubeMarine/blob/main/documentation/Installation.md#node_defaults), [account_defaults](https://github.com/Netcracker/KubeMarine/blob/main/documentation/Installation.md#rbac-account_defaults), [plugin_defaults](https://github.com/Netcracker/KubeMarine/blob/main/documentation/Installation.md#plugin_defaults) defaults sections from finalized inventory. This is safe because applying of defaults is an idempotent operation: once applied, the corresponding section in inventory will always redefine the defaults.
**TestCase 1**
Test …
=> [MANOPD-80329] Do not remove default sections from finalized inventory

kubemarine/plugins/__init__.py
Helm plugin now supports archives with helm charts with any depth of nested subdirectories.
Fixes #235 
**TestCase 1**
- OS: Any
Steps:
1. Configure helm plugin with public helm chart, for example
```yaml
plugins:
test:
install: true
installation:
procedures:
- helm:
chart_path: https://charts.bitnami.com/bitnami/wordpress-15.2.5.tgz
```
1. Run `bin/kubemarine install`
Results:
| No such file or directory: 'local_chart_folder/Chart.yaml' | Chart is installed successfully if properly configured |
=> MANOPD-80314 Support public helm charts

documentation/Installation.md, kubemarine/plugins/__init__.py
* It is not allowed to create few releases from the same Helm chart.
* Added option `release` to allow to specify custom release name.
Install Helm chart with arbitrary release.
**TestCase 1**
- OS: Any
Steps:
1. Configure Kubemarine helm plugin and specify arbitrary `release` option.
Results:
| Release is created with Helm chart name | Release is created with supplied custom name |
=> Add ability to specify custom Helm release name

documentation/Kubecheck.md, kubemarine/core/flow.py, kubemarine/procedures/check_paas.py
Added `check_paas` check which tests cross-clusters connectivity in DR schemas. This check uses `paas-geo-monitor` service from DRNavigator.
* `check_paas` now supports optional procedure.yaml
* new optional check `geo_monitor` is added
* documentation is updated accordingly
**TestCase 1**
- Two clusters in DR schema
Steps:
1. Run `check_paas` procedure with procedure.yaml for the new `geo_monitor` check
Results:
| -  | cross-cluster dns/connectivity check is performed |
=> [MANOPD-80122] check_paas DR clusters connectivity checks

kubemarine/resources/configurations/defaults.yaml
For medium and large clusters it's recommended to use `typha` in `calico` deployments to decrease number of calls to kubernetes api-server.
This PR is to change default `calico` settings.
MANOPD-80822
Default `calico` settings are changed. `typha` is enabled by default for clusters with more than 3 nodes and at least 2 replicas of `typha` are created for clusters with 4 nodes and more. With every 50 nodes number of `typha` replicas is incremented.
1. Deploy `calico` with default settings to the cluster with <= 3 nodes. Check that deployment finishes successfully, no `typha` installed, pods at different nodes can see each other.
2. Deploy `calico` with default settings to the cluster with more than 3 nodes. Check that deployment finishes successfully, `typha` pods are …
=> [MANOPD-80822] change default typha settings

documentation/Installation.md, kubemarine/templates/plugins/calico-v3.21.yaml.j2, kubemarine/templates/plugins/calico-v3.22.yaml.j2, kubemarine/templates/plugins/calico-v3.24.yaml.j2
By default typha pods cannot be scheduled to master nodes. In some cases it's necessary to allow typha pods to master nodes. So possibility to configure toleration for calico-typha pods is added.
Also added toleration to node.kubernetes.io/network-unavailable: NoSchedule|NoExecute. 
MANOPD-80822
Toleration is added for typha pods:
- key: node.kubernetes.io/network-unavailable
effect: NoSchedule
- key: node.kubernetes.io/network-unavailable
effect: NoExecute
Also added possibility to set additional tolerations in cluster.yaml
Deploy calico plugin.
1. Deploy calico at 4+ nodes cluster.
ER: Typha pods are scheduled and running and have toleration to node-role.kubernetes.io/network-unreachable (NoSchedule, NoExecute).
2. Add to cluster.yaml additional toleration settings, for …
=> [MANOPD-80822] adjust typha toleration settings and add toleration configuration option

documentation/Installation.md, kubemarine/admission.py, kubemarine/procedures/migrate_cri.py
* Workaround for `admission` makes changes implicitly
* `migrate_cri` procedure doesn't work for CentOS
* Delete workaround for `admission`
* Update documentation in Admission article
* Fix `migrate_cri`
The `cluster.yaml` must include `admission: pss` for successful running any procedure if Kubernetes has version 1.25
**TestCase 1**
The `migrate_cri` procedure works for CentOS
- Hardware: 2CPU/4GB
- OS: CentOS7
- Inventory: FullHA
Steps:
1. Install Kubernetes cluster with `containerRuntime: docker`
2. Run `migrate_cri` pricedure
Results:
=> [MANOPD-00000] Fix for Kubernetes 1.25 adoption

kubemarine/kubernetes/__init__.py, kubemarine/resources/configurations/defaults.yaml
* Failed CIS compliance checks for Kubernetes v1.23 
* Change in code to pass test validation
**TestCase 1**
Run check Kube-Bench
Steps:
1. Starting the cluster verification procedure
Results:
| Four failed tests | One failed test |
**Note** This test failed due to the non-support of the checker of this type of cluster. The developer has a ticket for this [problem](https://github.com/aquasecurity/kube-bench/issues/1275)
=> [MANOPD-80808]Failed CIS compliance checks for Kubernetes v1.23 deployed from Kubemarine 0.7.0

kubemarine/plugins/calico.py, kubemarine/resources/configurations/defaults.yaml
* `Calico` plugin installation fails in case of using a custom registry
* Change `defaults.yaml`
* Implement the image source processing with or without the custom registry
Not applicable
**TestCase 1**
Check if the fix works
Steps:
1. Run installation procedure. The `cluster.yaml` must have the following section:
```
plugin_defaults:
installation:
registry: <some-private-registry:port>
```
Results:
=> [MANOPD-81799] Fix images

kubemarine/plugins/calico.py, kubemarine/resources/configurations/defaults.yaml
* Installation on OpsPortal fails
* Transform the `calico_original_yaml` to the absolute path
Not applicable
=> [MANOPD-81799] Absolute path

kubemarine/procedures/check_paas.py, kubemarine/resources/configurations/defaults.yaml, kubemarine/resources/configurations/globals.yaml, kubemarine/thirdparties.py, test/unit/test_thirdparties.py
We've already had default sha for thirdparties, but we specially delete them. And then we skip sha check, if it's not defined in cluster.
* If default sha is not defined, for check caches thirdparty will be loaded to one of control-plane node and expexted sha will be got from this file.
* [Check Paas](documentation/Kubecheck.md#paas-procedure)
=> [MANOPD-77802] - Check default thirdparties sha despite of source

documentation/Kubecheck.md, kubemarine/apparmor.py, kubemarine/procedures/check_paas.py, kubemarine/system.py
* Apparmor validations and checks are necessary 
Resolves https://github.com/Netcracker/KubeMarine/issues/34
* Implement new tasks to `check_paas` for Apparmor status and configuration
* Implement `TODO` part in `system` module
* Fix `is_state_valid` and `parse_status` methods
Not applicable
**TestCase 1**
Check if the `check_paas` tasks work
- Inventory: Allinone
Steps:
1. Install Kubernetes cluster with Apparmor is enabled.
2. Run `check_paas` with tasks `services.security.apparmor`
3. Change Apparmor configuration on host.
4. Run `check_paas` with tasks `services.security.apparmor`
5. Disable Apparmor on host.
6. Run `check_paas` with tasks `services.security.apparmor`
Results:
| Not …
=> Apparmor check_paas

Dockerfile, requirements.txt, requirements_nt.txt
* Defective binary files build for linux systems due to an incompatible version of ansible for python 3.8
, this build is invalid and gives an error about the absence of the fabric module
https://github.com/Netcracker/KubeMarine/actions/runs/3640188892/jobs/6144533368
* Downgrade ansible version, raise fabric version and fix Dockerfile
Ansible
https://github.com/ansible-community/ansible-build-data/blob/main/6/CHANGELOG-v6.rst
=> [Hot fix]Build and check binary files

kubemarine/core/flow.py, kubemarine/procedures/check_iaas.py, kubemarine/procedures/check_paas.py, kubemarine/procedures/do.py
1. Help sections for procedures don't contain procedure name;
2. Help section for do procedure doesn't contain information about shell command;
3. Help section for do procedure runs with command `do -h --`;
4. Do procedure fails, if we don't add `-n` or `-g` options;
1. Procedure names were added to help sections;
2. Procedure names for chack-paas and check-iaas were renamed;
3. Help section for do procedure was updated;
4. Do procedure without `-n` and `-g` options was fixed;
5. Do procedure collects kubemarine options instead of remote options, if separator `--` is not defined;
No steps
**TestCase 1**
Steps:
1. Run …
=> [MANOPD-81950] - fix help sections

kubemarine/core/utils.py, kubemarine/plugins/__init__.py, kubemarine/plugins/calico.py, kubemarine/plugins/nginx_ingress.py, kubemarine/procedures/check_paas.py
Because of using jinja we have to support string true/false values. But for `plugins.<name>.install` we support only bool types.
As result  `plugins.<name>.install='false'` don't skip this plugin installation or `plugins.nginx-ingress-controller.install='true'` throws exception during cert renew procedure for ingress-nginx.
`true_or_false` function, what is used in calico plugin, was moved to utils. This function was used in conditional statements with `plugins.<name>.install`
**TestCase 1**
Steps:
1.  Add `plugins.kubernetes-dashboard.install='false'` to cluster.yaml;
2. Run installation procedure;
Results:
| kubernetes-dashboard is installed to cluster | kubernetes-dashboard isn't installed |
**TestCase 1**
Steps:
1.  Add …
=> [MANOPD-82181] - support string plugin.install values

kubemarine/procedures/check_paas.py
* `check_paas` procedure fails on `services.security.apparmor` tasks because of `get_os_family` method has been moved
* Change code
Not applicable
**TestCase 1**
Check if the tests work
- OS: Ubuntu 22
Steps:
1. Run `check_paas` procedure with `--tasks="services.security.apparmor"`
Results:
=> The AppArmor check fails

kubemarine/core/defaults.py, kubemarine/core/utils.py, kubemarine/plugins/__init__.py, kubemarine/plugins/calico.py, kubemarine/plugins/nginx_ingress.py, kubemarine/procedures/check_paas.py
Added missed check for undefined values
https://github.com/Netcracker/KubeMarine/pull/300
* 
* Manual step 
**TestCase 1**
- Hardware: 
- OS: 
- Inventory: 
Steps:
1. 
Results:
|  |  |
Indicate new or changed unit tests and what they …
=> verify undefined values for plugin.install

kubemarine/core/flow.py, kubemarine/procedures/add_node.py, kubemarine/procedures/backup.py, kubemarine/procedures/cert_renew.py, kubemarine/procedures/check_iaas.py, kubemarine/procedures/check_paas.py, kubemarine/procedures/install.py, kubemarine/procedures/manage_psp.py, kubemarine/procedures/manage_pss.py, kubemarine/procedures/migrate_cri.py, kubemarine/procedures/reboot.py, kubemarine/procedures/remove_node.py, kubemarine/procedures/restore.py, kubemarine/procedures/upgrade.py
In procedure help sections we don't have task list for this procedure.
Task list was added in the end of help section for all procedures with tasks
**TestCase 1**
Steps:
1.  Run `kubemarine <any procedure except do and migrate_kubemarine> -h`
Results:
| Help section **without** task list | Help section **with** task list |
Example:
```
$ kubemarine upgrade -h
usage: upgrade [-h] [-c CONFIG] [--ansible-inventory-location ANSIBLE_INVENTORY_LOCATION] [--dump-location DUMP_LOCATION] [--disable-dump] [--disable-dump-cleanup] [--log [LOG ...]] [-w WORKDIR]
[--without-act] …
```
=> [MANOPD-82386] - add task list in help section

requirements.txt
Connect to Ubuntu 22.04 via old paramiko version follows exception:
```
2022-12-21 14:30:24,212 test-mame-local-k8s.com DEBUG Start detecting nodes context...
2022-12-21 14:30:54,848 test-mame-local-k8s.com CRITICAL FAILURE!
2022-12-21 14:30:54,849 test-mame-local-k8s.com CRITICAL Failed to proceed inventory file
2022-12-21 14:30:54,849 test-mame-local-k8s.com CRITICAL KME0001: Unexpected exception
Traceback (most recent call last):
File "/mnt/c/Users/mame0719/Documents/Projects/PaaS/github/KubeMarine/kubemarine/core/resources.py", line 172, in _get_nodes_context
self._nodes_context = light_cluster.detect_nodes_context()
File "/mnt/c/Users/mame0719/Documents/Projects/PaaS/github/KubeMarine/kubemarine/core/cluster.py", line 175, in detect_nodes_context
self._check_accessible_nodes()
File …
```
=> [MANOPD-81458] - update paramiko version

kubemarine/resources/configurations/defaults.yaml
* Pods stuck in the "Terminating" status during redeploy and were in this state for a long time
* Add parameter **fs.may_detach_mounts=1** in **/etc/sysctl.conf**
Should be enabled on hosts where container runtimes are being used:
https://access.redhat.com/solutions/5430091
https://github.com/containerd/containerd/issues/3667#issuecomment-802373736
- OS: Linux
| Pods stuck in "Terminating" status during redeploy | When redeploying, "old" pods are terminating and do not stuck in this status |
=> [PSUPCLPL-11062] Update defaults.yaml

kubemarine/resources/configurations/globals.yaml
It ihas been identified during kubemarine operations that containerd 1.4 version might not be stable. 1.5 provided approved stable run.  Need to use 1.5 for new created clusters.
Fixes #MANOPD-82072 
* prepare.cri
=> [MANOPD-82072] fix containerd version

kubemarine/resources/configurations/defaults.yaml, kubemarine/resources/configurations/globals.yaml
Versions for local-path-provisioner and busybox are set in globals.yaml depending on k8s versions. On the other hand local-path-provisioner and busybox image version is hardcoded in defaults.yaml 
PSUPCLPL-11428
image version for local-path-provisioner and busybox in default.yaml set parametrized, depending on versions in globals.yaml
-
1. Deploy local-path-provisioner in k8s v1.25
ER: local-path-provisioner v0.0.23 is deployed. 
2. Deploy local-path-provisioner in k8s < v1.25
ER: local-path-provisioner v0.0.22 is deployed.
-
=> [PSUPCLPL-11428] Update defaults.yaml and global.yaml - parametrize local-path-provisioner and busybox image version

documentation/Maintenance.md
Sometimes it's necessary to change podSubnet at an existing cluster. This PR adds HowTo guide on this procedure.
PSUPCLPL-11380
Doc update
-
At an existing cluster go through the steps from /documentation/Maintenance.md#changing-cluster-cidr
ER: podSubnet in the cluster is changed, all the pods work fine.
-
=> [PSUPCLPL-11380] Doc update: how to change cluster CIDR guide

documentation/Maintenance.md
* By default, Kubernetes secrets are encoded with base64, which is not secure. To avoid potential revealing of sensitive data, the backend ETCD must be encrypted.
* Doc update
=> [MANOPD-81954] Data encryption

kubemarine/core/flow.py, kubemarine/procedures/install.py, kubemarine/procedures/reboot.py, kubemarine/procedures/restore.py, kubemarine/system.py, test/unit/core/test_flow.py, test/unit/test_demo.py
* KubeMarine performs unnecessary reboot during `install` procedure in some cases especially is cluster is reinstalled.
* Cumulative points are not executed if the related task is skipped, and the system is not verified in such cases.
* Remove unnecessary reboot schedule from disable swap.
* Fix packages changes detection for Ubuntu.
* Flow now always iterates over all tasks to proceed cumulative points, but only necessary tasks are finally run.
* Other refactoring, removed dynamic imports.
**TestCase 1**
- OS: Ubuntu
- Inventory: should contain non-empty `services.packages.install` section.
Steps:
1. Run `install` procedure twice.
Results:
| Both runs reboot the nodes | The second run should not reboot the nodes | …
=> Cumulative points fixes

kubemarine.spec, kubemarine/core/cluster.py, kubemarine/core/flow.py, kubemarine/core/resources.py, kubemarine/core/utils.py, kubemarine/kubernetes/__init__.py, kubemarine/kubernetes_accounts.py, kubemarine/plugins/kubernetes_dashboard.py, kubemarine/procedures/add_node.py, kubemarine/procedures/check_iaas.py, kubemarine/procedures/check_paas.py, kubemarine/procedures/do.py, kubemarine/procedures/install.py, kubemarine/procedures/remove_node.py, kubemarine/procedures/upgrade.py, kubemarine/resources/configurations/defaults.yaml, test/unit/core/test_run_actions.py, test/unit/test_kubernetes.py
* Need to print short summary after successful installation.
* Schedule different report items during run of particular tasks:
* Ready/Number of running Control Planes and Workers during `deploy.kubernetes.init` task of `install` procedure and corresponding tasks of `add_node`, `remove_node` procedures.
* Dashboard URL if `kubernetes-dashboard` plugin is (re)installed.
* Absolute path to account-tokens.yaml during `deploy.accounts` task of `install` procedure.
* Print all summary items just before exiting.
**TestCase 1**
- OS: Any
Steps:
1. Run `install` procedure.
Results:
| Not applicable | Summary is printed in the end of logs |
test_kubernetes.py - add test for parsing of `kubectl get node` …
=> MANOPD-82393 Final summary report

documentation/Troubleshooting.md
* Ubuntu 20.04 nodes have `NotReady` status spontaneously
* Update documentation
=> [MANOPD-82072] k8s nodes are "not ready" periodically

.gitignore, kubemarine/core/flow.py, kubemarine/core/summary.py, kubemarine/core/utils.py, kubemarine/kubernetes/__init__.py, kubemarine/kubernetes_accounts.py, kubemarine/plugins/__init__.py, kubemarine/plugins/kubernetes_dashboard.py, kubemarine/procedures/install.py, kubemarine/procedures/remove_node.py, test/unit/core/test_flow.py, test/unit/test_kubernetes.py
1. Need to fetch kubeconfig and print path to it in the installation summary.
1. Sometimes KubeMarine prints that 0 of N nodes are running after the installation.
1. Added fetching of the kubeconfig (/etc/kubernetes/admin.conf) during init of the first control-plane in `deploy.kubernetes.init` task.
1. Previously number of running control-planes / workers was fetched during `deploy.kubernetes.init` task in which the nodes are not yet ready. Implemented delayed collecting of summary information using improved cumulative points flow.
**TestCase 1**
- Inventory: FullHA
Steps:
1. Run `install`.
Results:
| Summary contains `Running Control Planes: 0/N` and no `Kubeconfig` | Summary contains `Running …
=> MANOPD-82393 Summary fixes and improvements

kubemarine/resources/configurations/globals.yaml, kubemarine/resources/schemas/definitions/plugins/local-path-provisioner.json
* Need update busybox in globals.yaml. Because there is no previous version on Docker HUB 
* Local-path-provisioner PVC stuck is not working correctly
* Need update json schemas
WA:
* Must be added to `cluster.yaml`. In the `plugins->local-path-provider` section, add the `helper-pod-image` parameter with the value `library/busybox:1.34.1`
* Restart pod local-path-provider
```yaml
plugins:
local-path-provisioner:
install: true
storage-class:
is-default: 'true'
helper-pod-image: library/busybox:1.34.1
```
* Update busybox in globals.yaml and json schema
=> [MANOPD-84427] : No busybox version 1.31.2

kubemarine/apt.py, kubemarine/packages.py, kubemarine/procedures/install.py, kubemarine/yum.py
* If attempt to remove already removed package on RHEL nodes, the reboot is scheduled.
* Added check of stdout output to skip reboot of RHEL nodes if nothing to remove or upgrade.
**TestCase 1**
- OS: RHEL OS family
- Inventory: contains `services.packages.remove` or `services.packages.upgrade`
Steps:
1. Run `install --tasks prepare.package_manager.manage_packages` twice.
Results:
| Both runs causes nodes to be rebooted | The second run does not reboot the nodes |
=> MANOPD-84124 Fix unnecessary reboot when nothing to remove / upgrade

documentation/Installation.md, documentation/Maintenance.md, kubemarine/kubernetes/__init__.py, kubemarine/procedures/upgrade.py, kubemarine/resources/configurations/defaults.yaml, kubemarine/resources/schemas/definitions/services/kubeadm.json, test/unit/test_thirdparties.py
* It is necessary to remove the default taint on nodes that have the roles of master and worker at the same time. Instead of the old procedure that removed these taints in the `apply_taints` procedure
* The procedure of deleting default taints on nodes having roles  of master and worker has been redesigned and transferred to another place (the moment of kubeadm init and join).
* Remove from `enrich_inventory` the procedure for adding standard taints for deletion in the `apply_taints` procedure.
* Update default.yaml
* Update documents
* Update Json schema
* Update unit test
* The possibility of updating to version 1.24.0 has been removed 
* When trying to upgrade to this version, an exception will be output
Please describe the tests that you ran to verify your changes. Provide …
=> Kubemarine: procedure for removing default taint on nodes having the roles of master and worker

kubemarine/patches/__init__.py, kubemarine/patches/p2_do_render_config.py
* KubeMarine declares that `do_render` is applicable only for `config` plugin procedure type, but technically it was possible to specify it for `template` procedure type.
* Provide automatic patch to change procedure type.
Run `migrate_kubemarine --force-apply do_render_config`
**TestCase 1**
- OS: Any
- Inventory: Has custom plugin(s) with `template` procedure type and `do_render` option.
Steps:
1. Run `migrate_kubemarine --force-apply do_render_config`
Results:
| Not applicable | `template` procedure type changes to `config` in the original inventory. |
=> Implemenent patch to change template to config plugin procedure type

.github/workflows/test_install.yaml
In test installation ci we copy dump files to separate directory after any operation. But it's better to use `--dump-location` option to reduce steps count.
At the same time github ci reject some symbols in file names to upload like artifact. For this reason was added additional steps to rename such symbols on `_`
* Use `--dump-location` instead of additional steps;
* Change not valid symbols before uploading;
* Manual step 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. …
=> Fix ci dump location

kubemarine/plugins/__init__.py, kubemarine/resources/configurations/globals.yaml
Installation/upgrade procedure doesn't fail on `deploy.plugins` task if the retries are exceeded for the following resources:
* `DaemonSet`
* `Deployment`
* `StatefulSet`
* `ReplicaSet`
* Add exception in `expect_` methods in `plugins` module
Not applicable
**TestCase 1**
Check if the fix works
- Inventory: MiniHA
Steps:
1. Run installation procedure. At least one predefined plugin must be enabled and it should not have enough time to run its main resource (one of the following: `DaemonSet`, `Deployment`, `StatefulSet`, `ReplicaSet`)
Results:
| Success | Fail with exception |
=> [MANOPD-84029] Status of resources

documentation/Troubleshooting.md
Troubleshooting Guide update: added `No Pod-to-Pod Traffic for Some Nodes` chapter.
PSUPCLPL-11755
Use `IP_AUTODETECTION_METHOD` to set proper network interface for calico routing.
Not applicable
-
-
=> [PSUPCLPL-11755] Update TG: add No Pod-to-Pod Traffic for Some Nodes

pyproject.toml
* `CryptographyDeprecationWarning: Blowfish has been deprecated` is printed in any Kubemarine procedure.
* Increase version of paramiko and freeze version of cryptography.
1. Run any procedure.
AR: `CryptographyDeprecationWarning: Blowfish has been deprecated` is printed in console logs.
ER: No warnings.
=> MANOPD-84442 Fix Blowfish deprecation warning

documentation/Installation.md
* Kubernetes cluster installation on `CentOS` images (with kernel <= `3.10.0-940.el7.x86_64`) fails on `Calico` (version `v3.24+`) plugin installation due to the `eBPF` feature absence.
* Update documentation
Not applicable
=> [MANOPD-85375] CentOS kernel and Calico compatibility

kubemarine/__main__.py, test/unit/test_keepalived.py
KubeMarine parses and produces yaml inventories with incorrect resolution of strings containing floating point numbers.
Make PyYAML resolve floating point numbers the same as ruamel.yaml does.
test_keepalived.py - added test to dump and load number-like password.
=> Fix resolution of exponential float by PyYAML

pyproject.toml, setup.py
* Une non-greedy '*?' to replace more than one link in the line.
* Specially process links within the current README page.
* Use short license identifier instead of full license text.
**TestCase 1**
1. Deploy package to PyPI.
2. Check that all links in README work.
=> Fix replacement of package README links

documentation/Installation.md, kubemarine/core/group.py, kubemarine/kubernetes/__init__.py, kubemarine/plugins/__init__.py, kubemarine/resources/configurations/defaults.yaml, kubemarine/resources/configurations/globals.yaml, kubemarine/resources/schemas/cluster.json, kubemarine/resources/schemas/definitions/globals.json, kubemarine/resources/schemas/definitions/node_defaults.json
Need to do the following improvements:
1. Add a separate timeout for expectation of daemonsets/deployments/replicasets/statefulsets readyness (now we have only one timeout pods.expect.plugins which is used for all of them and for pods).
2. Set higher default timeout for expectation of calico-node pods.
3. Add more sense in exception messages when daemonsets/deployments/replicasets/statefulsets/pods have not got ready within given timeouts (how to override default values of timeouts/retries).
4. Make some global timeouts configurable (nodes.ready, nodes.boot.defaults.timeout).
PSUPCLPL-11680
PSUPCLPL-11836
PSUPCLPL-11876
1. New global parameter is introduced:
```
deployments:
expect:
timeout: 5
retries: 30
```
which defines default values for `timeout` and `retries` in …
=> [PSUPCLPL-11680] adjust plugins and nodes timeouts

kubemarine/resources/configurations/globals.yaml
Old value of  `deployments.expect.retries` (30) is not enough to calico daemonset get up.
change `deployments.expect.retries` to 45 as it were for `pods.expect.plugins.retries`.
-
Run install job with `tasks=deploy.plugins`.
ER: plugins are installed successfully, timeout for daemonsets, deployments, statefulsets is 5*45=220s.
=> increase deployments.expect.retries

kubemarine/patches/__init__.py, kubemarine/patches/p2_fix_haproxy_user.py, kubemarine/templates/haproxy.cfg.j2
* On the cluster, Haproxy runs from root, you need to make it run not from root, but from the haproxy user
PDSDNREQ-7070
* Add new user and group parameters to `haproxy.cfg`
```
global
log                 127.0.0.1 local2 debug
user haproxy
group haproxy
```
run
```
kubemarine install --tasks="deploy.loadbalancer.haproxy.configure"
```
or 
use patch `p2_fix_haproxy_user.py`
**TestCase 1**
- Hardware: 
- OS: Ubuntu 20.04, 22.04, Centos 7
- Inventory: 
Steps:
1. 
Results:
| Haproxy running with Root | Haproxy running with non-Root |
=> [PDSDNREQ-7070] HAproxy running with Root, should move to non-root

documentation/Installation.md, kubemarine/resources/configurations/globals.yaml
* It is necessary to add support for the new version of kubernetes in kubemarine
* Kubernetes 1.26.3 support
* Added support for kubernetes version 1.26 in kubemarine
* Updated global.yaml
* Update Installation.md
**TestCase 1**
- Hardware: All-one
- OS: Centos,Ubuntu
- Inventory: Default 
Steps:
1. Install
Results:
| Not supported new version |  Supported new version |
=> [MANOPD-86195] K8s 1.26.3 support

documentation/Maintenance.md
* Migration procedure from PSP to PSS needs some details
* Doc update
Not applicable
=> [MANOPD-85384]Doc update

kubemarine/resources/configurations/defaults.yaml
As per external Pentest performed by the one of client, Kubernetes dashboard is missing some security headers.
We have added below missing security headers to the default configuration of dashboard ingress.
* X-Frame-Options
* X-Content-Type-Options
* Content-Security-Policy
* Adding below annotations for the dashboard-ingress in default configurations.
* Edit the configuration for the dashboard-ingress in kubernetes-dashboard namespace
* Add required headers in annotations as _configuration-snippet_. 
```
nginx.ingress.kubernetes.io/configuration-snippet: |   
add_header X-Frame-Options "sameorigin"; …
```
=> Added missing security headers

kubemarine/resources/configurations/globals.yaml
Please include a summary of the change and describe issue. Please also include relevant motivation and context.
* It is necessary to update the containerd version, as the support matrix for containerd has been updated [https://containerd.io/releases/#kubernetes-support](url) 
[MANOPD-85659]
* Globals.yaml has been updated
**TestCase 1**
- Hardware: All-in-one
- OS: Ubuntu 20.04, Ubuntu 22.04, Centos 7
- Inventory: Default
Steps:
1. Install
Results:
| old version containerd| new version containerd  |
=> [MANOPD-85659 ]Update Containerd version for all supported Kubernetes

documentation/Installation.md
Previously used public repo `devel:kubic:libcontainers:stable.repo` doesn't contain podman any more, so we have to install podman and containerd to RHEL8 in a different way.
PSUPCLPL-12043
Installation guide updated.
-
Deploy k8s at RHEL8 nodes from scratch according to IN.
ER: installation is successfull, podman and containerd are installed at the nodes.
=> [PSUPCLPL-12043] Doc Update - Installation guide: change RHEL prereqs

kubemarine/resources/configurations/defaults.yaml
As per external Pentest performed by the one of client, Kubernetes dashboard is missing some security headers.
We have added below missing security headers to the default configuration of dashboard ingress.
* X-Frame-Options
* X-Content-Type-Options
* Content-Security-Policy
PSUPCLPL-12085
* Adding below mentioned annotations for the dashboard-ingress in default configurations.
Steps how to apply on top previous Kubemarine version to execute on existing clusters
* Edit the configuration for the dashboard-ingress in kubernetes-dashboard namespace
* Add required headers in annotations as _configuration-snippet_. 
```
nginx.ingress.kubernetes.io/configuration-snippet: |
add_header X-Frame-Options "sameorigin";
add_header X-Content-Type-Options "nosniff";
add_header …
```
=> [PSUPCLPL-12085] Added missing security headers

kubemarine/core/utils.py
* `restore` after `add_node` fails with "[Errno 13] Permission denied"
* The reason is in '/tmp/kubemarine-backup.tar.gz' archive that is left after `add_node` procedure, belongs to root, and prevents uploading of different archive with the same name during `restore`.
* Use archives with different names for different purposes.
**TestCase 1**
Steps:
1. Run `install`, then `backup`, then `remove_node` & `add_node`, then `restore`.
Results:
| "[Errno 13] Permission denied" | Successful |
=> [MANOPD-86838] Resolve conflict of archive names in add_node and restore procedures

documentation/Installation.md, kubemarine/procedures/check_paas.py, kubemarine/thirdparties.py
* Fix the waiting forever while re-installation of third parties.
* Fix the `owner` and `mode` option for .zip thirdparties 
* Add check SHA of zip archive content.
https://github.com/Netcracker/KubeMarine/issues/365
* Adding parameter to **overwrite** the existing third parties which will prevent the code to go into forever waiting.
* Adding additional code for adding proper file _permission_ and _ownership_ after unpacking of .**zip** archives
* Adding additional code for verifying the **hash (SHA1)** for **zip archive** contents before and after unpacking.
**TestCase **
1. Run the re-installation of …
=> PSUPCLPL-11975 - Fix for issue #365

kubemarine/procedures/backup.py
* Restore over the newly installed cluster fails in `reboot` task with `kubectl` error: "Unable to connect to the server: x509: certificate signed by unknown authority".
* The reason is in absent /root/.kube/config file in list of files to backup.
* Add the missed /root/.kube/config file.
**TestCase 1**
Steps:
1. Run `install`, `backup`.
2. Rebuild VMs.
3. Run `install`, `restore`.
Results:
| Nodes did not become ready in the expected time | Success |
=> MANOPD-86915 Missed /root/.kube/config in backup & restore

documentation/Troubleshooting.md
In minha scheme Calico can detect vrrp for one of the nodes, if it uses default 'first-found' autodetect method. In that case pod-to-pod traffic from that node will lost.
Added new TG section, that describes possible way to resolve such situation.
* Manual step 
**TestCase 1**
Test Configuration: 
- Hardware: 
- OS: ubuntu
- Inventory: minha scheme
Steps:
Before: …
=> [MANOPD-86862] - add TG for vrrp in calico

documentation/Installation.md
In the documentation there is no description of supported parameters in `globals` section of cluster.yaml added in https://github.com/Netcracker/KubeMarine/pull/410.
Installation.md updated.
=> Doc update: add new parameters in globals section of IN

kubemarine/procedures/check_iaas.py
* It is necessary to add ports for checking in check_iaas for `calico metrics` and `prometheus` to work
[MANOPD-87367]
* Ports for `calico metrics` and `prometheus` have been added to the `check_iaas.py` check
=> [MANOPD-87367] Check_iaas procedure doesn't check tcp ports 9091, 9094 and 10254

kubemarine/procedures/check_paas.py
If we change kuber version in cluster.yaml and run `check_paas` procedure, `control_plane.configuration_status` fails with exception:
```
2023-04-11 10:26:53.064 +0300 Traceback (most recent call last):
2023-04-11 10:26:53.064 +0300   File "/usr/local/lib/python3.11/site-packages/kubemarine/procedures/check_paas.py", line 854, in control_plane_configuration_status
2023-04-11 10:26:53.064 +0300     if result[static_pod_name]['correct_version'] and \
2023-04-11 10:26:53.064 +0300        ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
2023-04-11 10:26:53.064 +0300 KeyError: 'correct_version'
2023-04-11 10:26:53.064 +0300   Control plane    ERROR?   220  configuration status ................................................................ 'correct_version'
```
We save only True …
=> [MANOPD-87294] - fix version check

documentation/Installation.md, documentation/Troubleshooting.md, examples/cluster.yaml/full-cluster.yaml, kubemarine/core/defaults.py, kubemarine/resources/configurations/defaults.yaml, kubemarine/resources/schemas/definitions/services/modprobe.json, kubemarine/system.py
Kubernetes installation on Ubuntu 22.04/20.04 fails if nodes have IPv6 network whereas installation on CentOS 7 works.
The error message is the following:
```
2023-03-28 08:31:40,903 47597 140540068624192 qa-fullha-kubernetes.openshift.sdntest.local VERBOSE [log.verbose] modprobe: WARNING: Module nf_conntrack_ipv6 not found in directory /lib/modules/5.4.0-146-generic
```
The reason is:
* Ubuntu 20.04/22.04 and CentOS 7 have different sets of kernel modules that should be applied during the installation in case of IPv6 usage
* Expand `defaults.yaml` for several sets of kernel modules that are stored in `services.modprobe`
* Add `services.modprobe` enrichment that must assume the OS family dependent procedure
* Change validation schema
* Update documentation
Add the OS family name into the …
=> [MANOPD-86649] Installation on IPv6 env fails

kubemarine/kubernetes/__init__.py
* Local `kubeconfig` has unreachable cluster URL in case of using IPv6. For instance:
```yaml
apiVersion: v1
clusters:
- cluster:
certificate-authority-data: <...data...>
server: https://2a03:7900:6:0:a00:27ff:fefb:e20f:6443
...
```
* Implement code changes that wrap IPv6 address in local version of `kubeconfig` into brackets
Not applicable since we do not have a lot of IPv6 installations
**TestCase 1**
Steps:
1. Run Kubernetes installation from IPv6 environment
2. Check the content of `kubeconfig` file that is allocated in `KubeMarine` running folder 
Results:
| wrong IPv6 URL format | correct IPv6 URL format  |
=> [MANOPD-87506] Wrong format for ipv6 address and port in kubeconfig

.github/workflows/ci.yaml, pyproject.toml
* ruamel.yaml.clib has universal2 build for macos11 arm64 that is in fact not a universal2, but for x84_64.
https://github.com/Netcracker/KubeMarine/issues/439
* WA: Fix dependency ruamel.yaml==0.17.22. That version has no transitive dependency on ruamel.yaml.clib for Python 3.11
=> Fix binary build for macos arm64

documentation/Maintenance.md, kubemarine/admission.py
* `manage_pss` procedure fails with error:
```
incorrect value for example-namespace-2, valid values: ['privileged', 'baseline', 'restricted']
```
`procedure.yaml`:
```yaml
pss: 
pod-security: enabled
namespaces: 
- example-namespace-2:
enforce: baseline
```
* Implementation `manage_pss_enrichment` and `label_namespace_pss` methods must match the `procedure.yaml` structure.
Not applicable
**TestCase 1**
Check if the fix works
Steps:
1. Run `manage_pss` procedure on existing cluster with the `procedure.yaml` similar the one that represented above
Results:
=> [MANOPD-82728]Complex namespaces in 'migrate_pss' procedure

documentation/Logging.md, kubemarine/core/log.py, kubemarine/procedures/check_iaas.py, kubemarine/procedures/check_paas.py, kubemarine/resources/configurations/globals.yaml, kubemarine/testsuite.py
TestCase and TestSuite classes from [testsuite.py](https://github.com/Netcracker/KubeMarine/blob/main/kubemarine/testsuite.py) always use colors to display text and background, even if `colorize=false` is specified in the arguments.
Now, when calling TestCase, execution arguments are also passed, after which `colorize=false` is checked  in them for stdout.
Also now in Windows, colors are also used by default. And the small doc update about using Windows Terminal in Windows for correct color display.
Run check_paas/check_iaas procedure with `colorize=false` for stdout
` kubemarine check_paas --log="stdout;level=warning;colorize=false"`
=> [MANOPD-87147] Improving colors

kubemarine/admission.py, kubemarine/core/cluster.py
After running manage_psp, manage_pss procedures `cluster_finalized.yaml` doesn't contain appropriate changes within `rbac:psp:pod_security`.
MANOPD-81667
Add `admission.update_finalized_inventory()` function which is called from to `core.cluster.make_finalize_inventory()`.
Not applicable
Deploy cluster with `pod-security: psp`.
Run `manage_psp` procedure with the following procedure.yaml:
```
psp:
pod-security: disabled
```
ER: job finishes successfully, `cluster_finalized.yaml` contains disabled psp:
```
...
rbac:
psp:
pod-seciruty: disabled
...
```
=> [MANOPD-81667] fix make_finalized_inventory

kubemarine/resources/configurations/globals.yaml
Updated golbals.yaml to add rhel_8.8 version in the supported os family.
Add RHEL 8.8 family
**TestCase 1**
Test Configuration: 
- OS: rhel_8.8
Steps:
1. Kubemarine check_iaas
AR: Check_iaas suceeded
2. Kubemarine install
AR: Installation suceeded
3. Kubemarine check_pass
AR: check_pass suceeded
4. kubemarine upgrade
create a procedure.yaml and add the version to be upgraded
upgrade_plan:
- v1.27.1
AR: Upgraded successfully
=> [MANOPD-88703] Added RHEL 8.8 support

documentation/Installation.md
* There is no pre-installed python on RHEL 8-based nodes.
* Therefore, `check_iaas` ends with a lot of warnings, since the tests require python installed on the nodes
* It is necessary adding python installation on nodes to the pre-installation requirements
[MANOPD-88830]
* New pre-installation requirements for RHEL 8 have been added to the documentation
=> [MANOPD-88830] Adding new requirements before installing a cluster on RHEL 8-based nodes

documentation/Installation.md, kubemarine/core/cluster.py, kubemarine/core/defaults.py, kubemarine/core/errors.py, kubemarine/core/executor.py, kubemarine/core/group.py, kubemarine/core/log.py, kubemarine/core/os.py, kubemarine/core/utils.py, kubemarine/jinja.py, kubemarine/kubernetes/__init__.py, kubemarine/kubernetes_accounts.py, kubemarine/plugins/__init__.py, kubemarine/procedures/backup.py, kubemarine/resources/configurations/globals.yaml, kubemarine/testsuite.py, test/unit/core/test_cluster.py, test/unit/core/test_env.py, test/unit/core/test_executor.py, test/unit/core/test_group.py, test/unit/plugins/test_template.py, test/unit/test_audit.py, test/unit/test_demo.py, test/unit/test_k8s_cert.py, test/unit/test_keepalived.py
* It is necessary to allow parameterization of the inventory file and plugin templates through the environment variables.
* Implemented API `core.os.Environ` to read-only access the environment variables.
* Added `env` variable referring to `Environ` to Jinja compilation context for inventory file and plugin templates.
* Implemented streaming of remote command's output to logging framework.
* Changed default logging format for stdout and `debug.log`
* Removed `cluster_name` from both formats
* Removed process and thread ID from `debug.log`.
**TestCase 1**
Environment variables in the inventory and plugin templates.
1. Configure inventory and/or plugin template with reference to environment variables in any section.
2. Run installation procedure.
ER: Environment variables are expanded and …
=> MANOPD-88483 Environment variables support in kubemarine cluster configuration

documentation/Installation.md, kubemarine/resources/configurations/defaults.yaml
IN contains an example of CoreDNS' `rewrite` plugin usage in `cluster.yaml` which doesn't work.
MANOPD-82304
* IN's updated. `rewrite` example is working now. Also updated information about `priority` parameter in `Corefile` config and an example of usage is added.
* Changed priority of CoreDNS template for AAAA queries rejection in non-IPv6 environments.
Not applicable 
Add `rewrite` plugin to cluster.yaml, for example:
```
services:
coredns:
configmap:
Corefile:
'.:53':
rewrite:
default:
data:
name:
- regex
- (.*)\.cluster-1\.local {1}.cluster.local
answer:
- name
- (.*)\.cluster\.local {1}.cluster-1.local
```
and run install job with task `deploy.coredns`.
ER: job finishes successfully, Coredns configmap contains rewrite section.
Indicate new or changed unit tests and …
=> [MANOPD-82304] IN update for CoreDNS rewrite plugin

documentation/Installation.md, documentation/Troubleshooting.md, kubemarine/plugins/nginx_ingress.py, kubemarine/resources/schemas/definitions/plugins/nginx-ingress-controller.json
Added the ability to specify arguments for ingress-nginx-controller in cluster.yaml
The need for this arose in PSUPCLPL-12540
Also added new issue to Troubleshooting.md
Run `kubemarine install --tasks="deploy.plugins"` with additional args for ingress-nginx-controller. For example:
```
...
plugins:
nginx-ingress-controller:
install: true
controller:
args: ['--disable-full-test', '--disable-catch-all']
```
=> [PSUPCLPL-12540] Ability to specify arguments for ingress-nginx-controller in cluster.yaml

kubemarine/resources/configurations/compatibility/internal/kubernetes_images.yaml, kubemarine/resources/configurations/compatibility/internal/packages.yaml, kubemarine/resources/configurations/compatibility/internal/plugins.yaml, kubemarine/resources/configurations/compatibility/internal/thirdparties.yaml, kubemarine/resources/configurations/compatibility/kubernetes_versions.yaml, scripts/ci/build_binary.py
Support Kubernetes 1.23.1 with the same compatibility map as for 1.23.6.
=> [PSUPCLPL-12873] Support Kubernetes 1.23.1

kubemarine/plugins/__init__.py
If using custom procedure with helm installation in new namespace of k8s cluster, you always get "CRITICAL KME0001: Unexpected exception". It happens because "`helm install`" calls  without flag `--create-namespace`
In **def apply_helm** kubemarine/plugins/__init__.py, line 788, add flag `--create-namespace`. It will not breaking procedure, because helm handle exception if namespace already exist.
=> Edit helm command to install chart in apply_helm function

kubemarine/plugins/nginx_ingress.py, test/unit/plugins/test_nginx_ingress.py
* Kubernetes v1.25+ installation fails on `ingress-nginx-controller` plugin step in case of `IPv6` stack usage. The error message:
```
The Service "ingress-nginx-controller" is invalid: spec.ipFamilies[0]: Invalid value: "IPv4": not configured on this cluster
2023-04-19 13:03:59,633 qa-all-in-one-kubernetes.openshift.sdntest.local CRITICAL FAILURE!
2023-04-19 13:03:59,638 qa-all-in-one-kubernetes.openshift.sdntest.local CRITICAL TASK FAILED deploy.plugins
2023-04-19 13:03:59,639 qa-all-in-one-kubernetes.openshift.sdntest.local CRITICAL KME0002: Remote group exception
2023-04-19 13:03:59,641 qa-all-in-one-kubernetes.openshift.sdntest.local CRITICAL 2*****************f:
2023-04-19 13:03:59,642 qa-all-in-one-kubernetes.openshift.sdntest.local CRITICAL 	Encountered a bad command exit code! …
```
=> [MANOPD-87510] Ingress-nginx-controller installation error (IPv6)

kubemarine/procedures/restore.py
If resolve.conf is not specified in the cluster.yaml file restore procedure was failing as chattr function is not supported to work with symbolic links.
Check for symlink  has been added. If it is a regular file procedure works as was designed.
If it is a symlink it restores without using chattr function.
Implement code changes.
**TestCase 1**
Steps:
Install cluster **with** resolv.conf section specified in cluster.yaml
Take backup of cluster
Restore cluster
Results:
**ER** - - Backup and restore finished successfully.
**AR** - - Backup and restore finished successfully.
**TestCase 2**
Steps:
Install cluster **without** resolv.conf section specified in cluster.yaml
Take backup of cluster
Restore cluster
Results:
**ER** - - Backup and restore finished successfully.
**AR** - - Backup and …
=> [MANOPD-85857] Fix chattr error.

documentation/Installation.md, kubemarine/resources/configurations/defaults.yaml
`serializeImagePulls: false`  allows parallel image pulling. 
There is only one recommendation when there is no need to use this, on nodes that run docker daemon with version < 1.9 or an aufs storage backend.
By default, this option is true.
MANOPD-90298
Parameter has been added to default.yaml, to allows parallel image pulling
1 - You need to add a parameter serializeImagePulls: false to config.yaml
Path /var/lib/kubelet/config.yaml
Example:
```
apiVersion: kubelet.config.k8s.io/v1beta1
...
serializeImagePulls: false
...
```
2 - You need to restart kubelet with the command:
`systemctl restart kubelet`
=> [MANOPD-90298] add "serializeImagePulls: false" by default to kubelet config

kubemarine/admission.py
* Removes an unnecessary block responsible for the PSP from the cluster_finalyzed.yaml of versions older than 1.24
MANOPD-88960
* Manual step 
**TestCase 1**
- Hardware: 
- OS: 
- Inventory: 
Steps:
1. 
Results:
|  |  |
=> [MANOPD-88960] Remove PSP from defaults for Kubernetes higher than 1.24 version 

kubemarine/kubernetes/__init__.py, kubemarine/procedures/migrate_cri.py, kubemarine/procedures/upgrade.py
*  kubeadm-flags.env file is not getting updated to reflect the upgrade version for pause.
* As per current design, this file not expected to update.
* Additional code required to update the upgraded version for pause image after successful upgradation of k8s version.
Fixes # 
[MANOPD-88293](https://psup.netcracker.com/browse/MANOPD-88293)
* Merging of this code will result in ability to update the upgraded version for pause image in **kubeadm-flags.env** file
during the upgrade procedure of kubemarine.
**TestCase 1**
Run the `kubemarine upgrade` procedure to upgrade the k8s version.
Results:
| **kubeadm-flags.env** file still shows the pause image version as per the older k8s version | **kubeadm-flags.env** file will be updated with the upgraded …
=> [MANOPD-88293] Update kubeadm-flags.env after successful upgrade of k8s version

kubemarine/kubernetes/__init__.py, kubemarine/procedures/install.py
* When we run the kube-bench on cluster running with k8s v1.27.1 installed using kubemarine 0.18.2, we got below failures-
```
[FAIL] 4.1.1 Ensure that the kubelet service file permissions are set to 600 or more restrictive (Automated)
```
**MANOPD-90205**
* Fix for 4.1.1 - Set to 600 or more restrictive permission on kubelet service file
**TestCase 1**
* Find the latest version of kube-becnh utility [https://github.com/aquasecurity/kube-bench/releases](url) 
* Upload archive to the master/worker node, for example
`scp -i ~/.ssh/shift_test_key ~/kube-bench_0.6.15_linux_amd64.tar.gz ubuntu@:/home/ubuntu`
* Unpack it to the separate folder
`tar -xvf kube-bench_0.6.15_linux_amd64.tar.gz`
* Run check as (latest Kubernetes Benchmark will be used by default …
=> [MANOPD-90205] fix for vulnerability scanning failures

README.md, documentation/Installation.md, examples/cluster.yaml/allinone-cluster-ol7.yaml, examples/cluster.yaml/allinone-cluster.yaml, examples/cluster.yaml/full-cluster.yaml, examples/cluster.yaml/miniha-cluster.yaml, examples/cluster.yaml/minimal-cluster.yaml, examples/cluster.yaml/typical-cluster.yaml, kubemarine/core/connections.py, kubemarine/core/utils.py, kubemarine/resources/schemas/definitions/gateway_node.json, kubemarine/resources/schemas/definitions/node_defaults.json
This change aims to enhance the kubemarine system by introducing support for both SSH key and SSH password authentication methods during installation, maintenance, and checks. Currently, only SSH key authentication is supported, and this change will provide users with the flexibility to choose their preferred authentication method.
* 
The current kubemarine system only supports SSH key authentication, which restricts users who prefer to use passwords for authentication or have systems that do not support SSH key-based authentication.
Updated Authentication Logic: Modify the code to handle both SSH key and SSH password authentication methods based on user-provided connection details.
* 
**TestCase 1**
1. Provide password instead of keyfile in cluster.yaml and proceed with …
=> [MANOPD-89259] Use_ssh_password_instead_of_ssh_key_in_k8s_installation

kubemarine/admission.py
Please include a summary of the change and describe issue. Please also include relevant motivation and context.
* Removes an unnecessary block responsible for the PSP from the cluster_finalyzed.yaml of versions older than 1.24
MANOPD-88960
* added a condition under which the PSP block will be removed from the cluster_finalyzed.yaml file if the kubernetes version is older than 1.24
Not applicable
Deploy clusterser older than 1.24
check cluster_finalyzed.yaml, there should not be a PSP block:
```
psp:
custom-policies:
bindings-list: []
psp-list: []
roles-list: []
oob-policies:
anyuid: enabled
default: enabled
host-network: enabled
pod-security: enabled
```
Indicate new or changed unit tests and what …
=> [MANOPD-88960] Remove PSP from defaults for Kubernetes higher than 1.24 version

documentation/Installation.md, kubemarine/resources/configurations/defaults.yaml, kubemarine/templates/haproxy.cfg.j2, test/unit/plugins/test_nginx_ingress.py
Without a proxy protocol, the x-forwarded-for header contains the IP of the load balancer, not the client IP
PSUPCLPL-12898
Enabling proxy protocol for ingress-nginx and HAProxy
1. Run `kubemarine install --tasks="deploy.loadbalancer.haproxy.configure,deploy.plugins"` for exist cluster or create new one
2. Check the ingress-nginx-controller configmap, it should contain `"use-proxy-protocol": "true"`.
3. Check configuration of HAproxy, it should contain `send-proxy`  for servers in http/https_backend.
`"use-proxy-protocol": "true"` has been added to ./test/unit/plugins/test_nginx_ingress.py for testing configmap.
=> [PSUPCLPL-12898] Enabling proxy protocol for ingress-nginx and HAProxy

kubemarine/patches/__init__.py, kubemarine/patches/p1_kubeadm_flags.py
* Patch for updating --pod-infra-container-image version in /var/lib/kubelet/kubeadm-flags.env file
* MANOPD-88293
* Apply this patch for the old clusters where --pod-infra-container-image version was not updated in /var/lib/kubelet/kubeadm-flags.env file even after k8s upgrade.
* [Install task/s](https://github.com/Netcracker/KubeMarine/blob/main/documentation/Maintenance.md#kubemarine-migration-procedure)
**TestCase 1**
Steps:
1. Try to upgrade k8s for e.g. from _v1.24.11_ to _v1.25.2_ or _v1.25.2_ to _v1.26.4_ (where pause image version should be new between the versions) using tag 0.18.2 or older.
2. With such upgrade, the pause version for ` --pod-infra-container-image` will not get updated in the `/var/lib/kubelet/kubeadm_falgs.env` file.
4. Then apply this patch …
=> patch for kubeadm_flags

kubemarine/__main__.py, kubemarine/procedures/check_iaas.py, kubemarine/procedures/check_paas.py
* Due to the previous changes in check paas, the internal gitlab ci was broken. (https://github.com/Netcracker/KubeMarine/pull/426)
* Therefore, internal gitlab ci is not working right now.
* Because the context return from the function was removed in check paas and check iaas.
* The code was refactored in check paas and check iaas, context output was added to the function
=> Refactoring Check Paas, Check IaaS tests

kubemarine/core/group.py, kubemarine/procedures/check_paas.py, kubemarine/thirdparties.py
Restore procedure skips thirdparties that are managed by plugins. If restore procedure reverts older versions of plugins, new versions of thirdparties reside on the nodes, thus introducing a mismatch. By default, this is relevant for `calicoctl `.
Restore all thirdparties including those that are managed by plugins.
**TestCase 1**
Restore `calicoctl ` executable.
Steps:
1. Install Kubernetes v1.26.3
2. Take backup
3. Upgrade to Kubernetes v1.26.4
ER: `calico` is upgraded from v3.24.2 to v3.25.1
4. Restore from backup taken at step 2.
5. Run `check_paas`.
Results:
| `thirdparties.hashes` fails with "expected sha is not equal to actual sha for /usr/bin/calicoctl" |  `thirdparties.hashes` is successful |
**TestCase 2**
Check mismatch of client and …
=> [PSUPCLPL-13194] Restore calicoctl executable

kubemarine/core/utils.py, kubemarine/procedures/check_iaas.py, kubemarine/procedures/check_paas.py, pyproject.toml
Remove dependency on useful-types as it does not support python 3.7
=> Fix CI workflows

.github/workflows/ci.yaml
* Binary build on macos11 sometimes fails with `AssertionError: The script relies on internal implementation of pip and was tested on pip==23.0. To support pip==23.2.1, the script should be manually adopted.`, but we have explicit installation of `pip install pip==23.0` one step before.
* Root cause is in incorrect pip installation. `find /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages -name 'pip-*.dist-info'` shows two versions of the package:
```
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip-23.1.2.dist-info
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip-23.2.1.dist-info
```
https://github.com/actions/setup-python/issues/713
* Add step to remove orphaned installation.
=> CPDEV-91439 Work around broken pip installation on GitHub macos11 VM

kubemarine/core/cluster.py, kubemarine/core/connections.py, kubemarine/core/executor.py, kubemarine/core/group.py, kubemarine/core/resources.py, kubemarine/core/utils.py, kubemarine/demo.py, kubemarine/procedures/backup.py, kubemarine/resources/configurations/globals.yaml, test/unit/test_backup.py
* `export.kubernetes` task of `backup` procedure works long.
* Use one `kubectl` invocation to get all resources for the particular namespace, instead of multiple `kubectl && kubectl` invocations.
* Implement custom parsing of the resulting yaml list to split resources of different kinds into different files.
* Use 2 background tasks for all available control planes to invoke few `kubectl` commands in parallel.
* Use `gzip` to compress data before sending through the network.
* Use dedicated parsing background task to ensure that only one thread loads the data in memory.
**TestCase 1**
1. Run `backup` or `backup --tasks export.kubernetes,pack` on large cluster
ER: elapsed time for the `export.kubernetes` task decreases 10 times or more.
test_backup.py - added test for `export.kubernetes` …
=> PSUPCLPL-13194 Optimize downloading of Kubernetes resources during backup

kubemarine/admission.py
* After adding a new version of kubernetes 1.28, it is necessary to correct the operation of the `manager_pss` procedure for the correct operation of the new version of kubernetes, since the `PODsecurity` argument for `kube-apiserver` was set in the new version of kubernetes.
* More information about this problem in https://github.com/kubernetes/kubernetes/pull/114068 or https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.28.md
CPDEV-91748
CPDEV-91752
* The procedure for installing and removing PSS for a cluster on kubernetes 1.28 has been redesigned
=> [CPDEV-91748][CPDEV-91752] Fix procedure install and delete PSS for Kubernetes v1.28

documentation/Installation.md, documentation/Kubecheck.md, kubemarine/kubernetes/__init__.py, kubemarine/patches/__init__.py, kubemarine/patches/p4_reconfigure_audit_policy.py, kubemarine/procedures/check_paas.py, kubemarine/procedures/install.py, kubemarine/procedures/upgrade.py
* We use not recommended `--config` option during kubeadm upgrade. This leads to incorrect upgrade in some cases when etcd, kube-apiserver become bound to incorrect IP.
* `prepare.system.audit.configure_policy` installation task reconfigures api-server and goes before Kubernetes reset. This makes it impossible to re-install the cluster over the existing one in some cases, because api-server cannot start.
* `configure_policy` task of upgrade procedure is redundant as the audit configuration does not depend on the Kubernetes version. It also performs partial upgrade of api-server component only that leads to undefined behaviour in some cases.
Fixes #456
Fixes #213
* Do not change audit policy configuration during the upgrade. Instead, create patch that will configure audit policy once to …
=> [CPDEV-91646] Fixes and improvements of Kubernetes audit policy maintenance

.github/workflows/integration_tests.yaml, ci/default_cluster.yaml, ci/extended_cluster.yaml, documentation/Troubleshooting.md
According issue https://github.com/Netcracker/KubeMarine/issues/496, in some cases, proxy protocol should be disabled.
* Added section in troubleshooting guide with proxy protocol section. There are described a possible cases, when such problem can appear, and possible solutions.
* Added connectivity checks to default and extended ci installation, to handle ingresses problem in future;
* To make connectivity check work, added proxy protocol disabling in tests;
**TestCase 1**
Test Configuration: 
- Hardware: 
- OS: 
- Inventory: all-in-one without balancers;
Steps:
1. Run `kubemarine install`;
Results:
| with proxy protocol enabled | with proxy protocol disabled |
| ingress connectivity failed | ingress connectivity passed |
**TestCase 2**
Test …
=> Add proxy protocol issue in troubleshooting guide

kubemarine/admission.py, kubemarine/procedures/upgrade.py
* In the new version of kubernetes(1.28), the `PODsecurity` argument for kube-apiserver has been deprecated and removed in new versions.
* More information about this problem in https://github.com/kubernetes/kubernetes/pull/114068 or https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.28.md
* When updating from kubernetes version 1.27 to version 1.28 with the feature-gates argument removed, the update failed with the error `"KeyError: 'feature-gates'"`.
* It is necessary to add a check for the presence of this argument before the update procedure.
[CPDEV-91812]
* Added a new check for the presence of the feature-gates parameter before upgrading to kubernetes version 1.28
=> [CPDEV-91812] Upgrade to 1.28.0 procedure fails - KeyError: 'feature-gates'

kubemarine/admission.py, kubemarine/plugins/builtin.py, kubemarine/plugins/calico.py, kubemarine/plugins/kubernetes_dashboard.py, kubemarine/plugins/local_path_provisioner.py, kubemarine/plugins/manifest.py, kubemarine/plugins/nginx_ingress.py
* Facing `Error from server (NotFound): namespaces "calico-apiserver" not found` when trying to enable PSS if Calico API server is not installed.
* `admission.label_namespace_pss` now takes into account if some namespaces from some manifests are not installed.
* Additional improvement: `admission.label_namespace_pss` now follows the plugins installation procedure and does not set labels when they are not necessary. It also removes unnecessary labels if less restrictive PSS profile is installed.
**TestCase 1**
Enable PSS when Calico API server is not installed.
1. Install cluster with `rbac.pss.pod-security=disabled`.
2. Enable PSS using `manage_pss`.
Results:
| Error from server (NotFound): namespaces "calico-apiserver" not found | PSS is enabled | …
=> CPDEV-93439 Cannot enable PSS without calico-apiserver

.github/workflows/tests.yaml
* If license is inserted as the last commit of PR, the PR has no workflow run. This does not allow to apply status checks to pass before merging.
Fixes #422
* Insert license only main and other protected branches.
=> [CPDEV-91476] Insert license only to protected branches

kubemarine/core/defaults.py, kubemarine/core/flow.py, kubemarine/core/utils.py, kubemarine/kubernetes/__init__.py, kubemarine/procedures/backup.py, kubemarine/procedures/restore.py, test/unit/core/test_schema.py, test/unit/test_restore.py
* If backup.tar.gz for restore procedure holds different Kubernetes version, it is not reflected in final cluster.yaml.
* `prepare.verify_backup_data` task is now always done during enrichment, so Kubernetes version is always enriched.
* `prepare.unpack` task is now always done before enrichment.
* Recreate inventory with the version that is restored from backup.
**TestCase 1**
Backup and restore to the previous Kubernetes version. Check final inventory.
Steps:
1. Install kubernetes and make backup.
2. Upgrade to new version.
3. Restore using the backup archive.
ER: thirdparties are installed for old version. Old version is restored.
4. Check the resulting cluster.yaml.
Results:
| Still holds new Kubernetes version | Holds old Kubernetes version | …
=> [CPDEV-93723] Restore from backup holding another Kubernetes version

.github/workflows/integration_tests.yaml, kubemarine/procedures/check_paas.py
During `check_paas` tests it would be useful to check not only `kubernetes-dashboard` service, but also `kubernetes-dashboard` ingress.
CPDEV-93091
`kubernetes_dashboard_status` function is updated with the check of the ingress similar way as it was done for the service.
The ingress is being checked only after successful check of the service.
To make the ingress check possible in an environment without proper DNS settings, the curl's `--resolve` flag is used.
The ingress name is being resolved to the cluster.inventory['control_plain']['internal'] and the check is running from one of master nodes.
Not applicable
1. Deploy a cluster with `kubernetes-dashboard` plugin. Run `check_paas` procedure with `--tasks=kubernetes.plugins.dashboard` flag.
ER: The test is successful, …
=> [CPDEV-93091] Add dashboard ingress check to check_paas dashboard test

documentation/Maintenance.md, kubemarine/core/defaults.py, kubemarine/core/utils.py, kubemarine/procedures/restore.py, kubemarine/thirdparties.py, test/unit/test_restore.py
* We need to restore dns configuration before working with internet resources, i. e. do it before restore.thirdparties task.
* `restore_plan.thirdparties` are not present in final inventory.
Fixes #482
* Add new task `restore.dns.resolv_conf` that restores the resolv.conf, and that is run before `restore.thirdparties`.
* Move enrichment of thirdparties from `restore.thirdparties` task to enrichment procedures.
**TestCase 1**
Restore resolv.conf before thirdparties.
Steps:
1. Configure cluster.yaml in private environment with `services.resolv.conf` section, and install the cluster.
2. Take backup
3. Truncate /etc/resolv.conf
4. Restore from backup.
Results:
| `restore.thirdparties` task failed | Restore is successful  |
**TestCase 2**
Enrich …
=> [CPDEV-94061] Restore resolv.conf before restoring of thirdparties

kubemarine/core/defaults.py, kubemarine/cri/containerd.py, kubemarine/patches/__init__.py, kubemarine/patches/p4_reinstall_etcdctl_thirdparty.py, kubemarine/resources/scripts/etcdctl.sh
This PR fixes the bug, related to PR https://github.com/Netcracker/KubeMarine/pull/523:
If user specifies only new format configuration (without credentials), `hosts-dir` flag is not applied for ctr commands.
Example of configuration:
```yaml
services:
kubeadm:
imageRepository: registry.example:9090
cri:
containerdRegistriesConfig:
registry.example:9090:
host."http://registry.example:9090":
capabilities: [ "pull", "resolve" ]
skip_verify: true
```
As result ctr fails with pulling problem like:
```
failed to do request: Head \"https://registry.example:9090/v2/pause/manifests/3.9\": http: server gave HTTP response to HTTPS client" host="registry.example:9090"
ctr: failed to resolve reference "registry.example:9090/pause:3.9": failed to do request: Head …
```
=> [CPDEV-94111] - fix ctr flags for new containerd format

documentation/Maintenance.md, documentation/Troubleshooting.md, kubemarine/k8s_certs.py
*  `kubelet` server uses self-signed certificate by default
* It needs to describe how to use default Kubernetes cluster CA to sign the `kubelet` server certificates within the cluster
Not applicable
**TestCase 1**
Check if the installation procedure finishes successfully with the settings from the article
- Inventory: AllinOne
Steps:
1. Add to `cluster.yaml` the following part:
```
services:
kubeadm_kubelet:
serverTLSBootstrap: true
rotateCertificates: true
kubeadm:
apiServer:
extraArgs:
kubelet-certificate-authority: /etc/kubernetes/pki/ca.crt
```
2. Run installation
Results:
| Success | Success |
**TestCase 2**
Check if the `cert_renew` procedure finishes successfully with the settings …
=> Kubelet server certificate improvement

documentation/Maintenance.md, kubemarine/controlplane.py, kubemarine/core/cluster.py, kubemarine/core/defaults.py, kubemarine/core/resources.py, kubemarine/core/utils.py, kubemarine/haproxy.py, kubemarine/keepalived.py, kubemarine/kubernetes/__init__.py, kubemarine/patches/__init__.py, kubemarine/patches/p0_bind_vrrp_ips_interfaces.py, kubemarine/procedures/add_node.py, kubemarine/procedures/install.py, kubemarine/procedures/remove_node.py, kubemarine/resources/schemas/add_node.json, kubemarine/system.py, test/unit/core/test_flow.py, test/unit/test_coredns.py, test/unit/test_defaults.py, test/unit/test_inventory.py, test/unit/test_keepalived.py, test/unit/test_remove_node.py, test/unit/test_thirdparties.py
1. Incorrect calculation of `control_plain` section based on VRRP IPs.
1. Keepalived can be installed on not balancer, but not working due to dependency on HAProxy.
1. Incorrect configuration of VRRP IP on nodes on which it is not assigned to.
1. VRRP IPs should not be touched in user inventory to make remove_node & add_node procedures reversible.
1. If `vrrp_ips.interface` is explicitly specified, it does not work for few VRRP IPs.
1. Removing of offline balancers does not work.
1. Removing of nameless nodes does not work.
1. certSANs are duplicated in enriched inventory and incorrectly handled in cluster_finalized.yaml
Fixes #248
1. Removed or absent hosts should not be taken into account during calculation of `control_plain` by VRRP IPs.
1. Keepalived can be installed only on balancers …
=> [CPDEV-84690] Improvement and fixes in Keepalived installation and removing balancers

documentation/Maintenance.md, kubemarine/procedures/backup.py
* Backup procedure does not backup custom apt repositories.
Fixes #282
* Add `/etc/apt/sources.list.d/` to the list of directories to backup.
**TestCase 1**
Backup and restore custom apt repo.
Steps:
1. Install the cluster with custom `services.packages.package_manager.repositories`
2. `apt show` some package from some of there repos.
3. Run backup.
4. Remove the repos from nodes manually or using Kubemarine.
5. `apt show` the same package.
ER: package is shown.
7. Run restore.
8. `apt show` the same package.
Results:
| Package is not shown | Package is shown  |
=> [CPDEV-94459] Backup custom apt repositories

documentation/Kubecheck.md, kubemarine/audit.py, kubemarine/demo.py, kubemarine/procedures/check_paas.py, kubemarine/procedures/install.py, kubemarine/sysctl.py, kubemarine/system.py, test/unit/test_audit.py
* Need to add validation of kernel parameters and audit rules.
Fixes #42
* Added validation of already configured sysctl parameters and audit rules during the `install` procedure.
If they are actual, the configuration is skipped.
* After #331 we no longer need reboot before configuring of sysctl.
Reboot and `verify_system` now happen after configuring of sysctl.
Added validation that sysctl parameters are still actual after reboot.
* Added PaaS checks of sysctl parameters and audit rules.
**TestCase 1**
Double installation skips configuration of kernel parameters and audit rules.
Steps:
1. Install the cluster, and then run `install` procedure to reinstall the cluster.
Results:
| sysctl parameters and audit rules are always reconfigured | sysctl …
=> [CPDEV-94486] Add sysctl and audit rules validation

documentation/Troubleshooting.md
* Upgrade to Kubernetes v1.28.3 from previous v1.28 versions fails
Fixes #544 
* Troubleshooting guide update
Not applicable
**TestCase 1**
Check if the solution works
- Inventory: AllinOne
Steps:
1. Install Kubernetes v1.28.0 (or upgrade to v1.28.0 from v1.27.x) via `KubeMarine`
2. Change `/etc/kubernetes/manifests/etcd.yaml` as it's described in TG
3. Run the upgrade procedure via `KubeMarine`
Results:
=> [CPDEV-94593] Upgrade to v1.28.3 issue

documentation/Troubleshooting.md
* Troubleshooting guide suggests how to resolve some problem with Kubernetes audit during upgrade, but we no longer touch audit configuration during upgrade after #495
=> Remove outdated troubleshooting guide

documentation/Installation.md, kubemarine/patches/__init__.py, kubemarine/patches/p1_set_sysctl_variables.py, kubemarine/procedures/install.py, kubemarine/resources/configurations/defaults.yaml
There are recommendations from Calico developers about [NetworkManager configuration](https://docs.tigera.io/calico/latest/operations/troubleshoot/troubleshooting#configure-networkmanager) and [nf_conntrack_max setting](https://docs.tigera.io/calico/latest/operations/troubleshoot/troubleshooting#configure-networkmanager).
CPDEV-50513
1. The `net.netfilter.nf_conntrack_max` kernel variable is set to `1000000` in the `defaults.yaml`. The Installation Guide is updated accordingly.
2.  New networking prerequisite is added in the Installation Guide for the case when NetworkManager is in use.
3.  A patch to align cluster with new default sysctl settings is added.
Run `kubemarine migrate_kubemarine` for the patch `set_sysctl_variables`. 
1. Deploy k8s cluster with the latest …
=> [CPDEV-50513] Add nf_conntrack_max and NetworkManager config recommended for calico

kubemarine/patches/p1_set_sysctl_variables.py, kubemarine/resources/configurations/defaults.yaml
After adding `net.netfilter.nf_conntrack_max` kernel variable setting in the `defaults.yaml` installation fails because this variable cannot be set until `nf_conntrack` kernel module is loaded. It's loaded by kubernetes when a node is joining to the cluster, but sysctl variables are configured before kubernetes deployment.
CPDEV-95071
Add `nf_conntrack` to all the lists `services.modprobe.<OS_FAMILY>`.
In case of fresh installation, just install k8s with kubemarine.
In case of running environment, run `kubemarine migrate_kubemarine`.
1. Deploy k8s cluster with the latest kubemarine.
ER:
`net.netfilter.nf_conntrack_max=1000000` (check with `sysctl net.netfilter.nf_conntrack_max`)
2. Deploy cluster with the previous kubemarine version.
Run `sysctl …
=> [CPDEV-95071] Add nf_conntrack to the list of modprobe's modules

kubemarine/modprobe.py, kubemarine/procedures/check_paas.py, kubemarine/procedures/install.py, kubemarine/system.py
* Re-installation of the cluster fails if the cluster was installed by old Kubemarine.
Error: "Required kernel parameters are not presented"
* Root cause is in `net.netfilter.nf_conntrack_max` kernel parameter. The parameter is not loaded at startup as the module `nf_conntrack` is not yet loaded. Conversely, during the installation the module is already loaded, returned by `lsmod` and modprobe is thus not reconfigured.
* In `prepare.system.modprobe` task verify not only that `lsmod` returns the module, but also that `/etc/modules-load.d/predefined.conf` is actual.
**TestCase 1**
Re-installed the cluster that was installed by old Kubemarine.
1. Install the cluster using Kubemarine v0.23.0.
2. Re-install the cluster using new Kubemarine.
Results:
| …
=> [CPDEV-95240] Reconfigure modprobe if configuration is outdated

kubemarine/patches/__init__.py, kubemarine/patches/p0_bind_vrrp_ips_interfaces.py, kubemarine/patches/p1_set_sysctl_variables.py
* Since v0.24.0 is yanked, need to create new release with the same patches.
Run `kubemarine migrate_kubemarine`.
See
* Test Cases from #546
* TestCase 8 from #532
=> Return patches from v0.24.0

documentation/Maintenance.md, kubemarine/procedures/backup.py, kubemarine/resources/schemas/backup.json, test/unit/test_backup.py
Exported kubernetes objects in `backup` procedure are not used in `restore` procedure, but they take a lot of time to export (especially in big clusters). They can be helpful only for some manual changes, but they do not needed by default.
Additionally now user can't skip kubernetes resources export in `procedure.yaml`, because it's not allowed in json schema. He can only skip whole task. 
And finally user can't export only specific resource because of the same reason. For example the following configuration is restricted:
```yaml
backup_plan:
kubernetes:
namespaced_resources:
namespaces: all
resources:
- configmaps
nonnamespaced_resources: []
``` 
* Fixed json schema and backup procedure itself to process empty list of resources and namespaces;
* Fixed defaults for …
=> [CPDEV-93171] - do not export kubernetes resources by default

documentation/Maintenance.md, kubemarine/procedures/upgrade.py, test/unit/test_upgrade.py
During upgrade procedure kubeadm creates special [backup files](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/#recovering-from-a-failure-state), that are used for manual restoration.
But no one uses or cleans those files, for this reason they are not really needed and only take up the place on the disk.
* Added the special task, that cleans up that directory before upgrade procedure; As result backups only for the last upgrade will be in that directory after the procedure;
* Added information about it in documentation;
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any
**TestCase 1**
- Hardware: 
- OS: 
- Inventory:
Steps:
1. run `kubemarine …
=> [CPDEV-93171] - clean kubernetes tmp dir before upgrade

kubemarine/procedures/upgrade.py
The command, provided in the PR https://github.com/Netcracker/KubeMarine/pull/557 does not work for not-root user.
In that case it does nothing, because `-f` option is used and backup files still exist in the nodes.
Without `-f` option the following exception appears:
```
$ sudo rm -r /etc/kubernetes/tmp/*
rm: cannot remove '/etc/kubernetes/tmp/*': No such file or directory
```
The problem is in `*`, because shell tries to expand, but can't do it without read permissions `sudo` doesn't help in that case.
This `/etc/kubernetes/tmp` directory uses 700 grants, for this reason not-root user does not have read grants for it.
For this reason the command should be rewritten not to use `*`.
Fixed command to work with not-root user
Please describe the tests that you ran to verify …
=> [CPDEV-95434] - fix cleanup command

documentation/internal/Hardening.md
* We use `kube-bench` to make `KubeMarine` CIS aligned. Some of the improvements do not support in source code and could be applied manually.
* The suggested improvements have be reproduced
* Some additional observation in CIS scan which needs to be added in the hardening guide
* Update the guide (hardening) in `KubeMarine` documentations
Not applicable
After applying the changes mentioned in this PR, run the kube-bench scan and verify result for identifier 1.2.31.
* Login to one of the master node of the cluster on which it is going to be tested
* Download `kube-bench_0.6.17_linux_amd64` package from `https://github.com/aquasecurity/kube-bench`
* Install downloaded pkg using `sudo dpkg -i kube-bench_0.6.17_linux_amd64.deb`
* Run scan using command - `kube-bench` and check for identifier …
=> [PSUPCLPL-13377] Instructions for cryptographic cipher suites

kubemarine/admission.py, kubemarine/core/defaults.py, kubemarine/core/utils.py, kubemarine/jinja.py, kubemarine/kubernetes/__init__.py, kubemarine/kubernetes_accounts.py, kubemarine/procedures/check_paas.py, kubemarine/procedures/upgrade.py, kubemarine/resources/configurations/defaults.yaml, scripts/thirdparties/src/compatibility.py, test/unit/test_upgrade.py
* The PR is intended to support Kubernetes release candidate testing.
* `utils.version_key` takes into account versions like `v1.29.0-rc.1`
* Use `kubemarine.utils` everywhere where necessary to work with versions.
**TestCase 1**
Steps:
1. Add `v1.29.0-rc.1` to `kubernetes_versions.yaml` compatibility map.
2. Run `scripts/thirdparties/sync.py`.
ER: the script succeeds
=> [CPDEV-95723] Support release candidate version

documentation/Installation.md, kubemarine/kubernetes/__init__.py, kubemarine/resources/configurations/defaults.yaml, kubemarine/resources/schemas/definitions/services.json, kubemarine/resources/schemas/definitions/services/kubeadm_kube-proxy.json
* Support [KubeProxyConfiguration](https://kubernetes.io/docs/reference/config-api/kube-proxy-config.v1alpha1/#kubeproxy-config-k8s-io-v1alpha1-KubeProxyConfiguration)
* **Note** that this is still an alpha feature.
* Added `services.kubeadm_kube-proxy` that directly converted to the KubeProxyConfiguration for `kubeadm init`.
**TestCase 1**
Configure custom properties in  `services.kubeadm_kube-proxy`.
Steps:
1. Configure custom properties in  `services.kubeadm_kube-proxy` and install the cluster.
ER: The properties are handled respectively. Check at least `kubectl get cm -n kube-system kube-proxy -o yaml`.
=> [CPDEV-95920] Support KubeProxyConfiguration as services.kubeadm_kube-proxy section

documentation/Troubleshooting.md
kubemarine image can be not compatible with user docker version. In that case some command in kubemarine docker container fails with ` Operation not permitted` error.
Added new TG section, that describes, how to resolve this issue.
=> [PSUPCLPL-14291] - add new TG section for kubemarine docker run issue

documentation/Installation.md, kubemarine/jinja.py
It's not obvious, how to specify credentials for thirdparties/packages registries, especially using environment variables.
* Added some descriptions and examples, how to use secure registries in kubemarine;
* Added some jinja functions, that can be useful for credentials managing (they are used in provided examples);
=> [CPDEV-96370] - add secure registries doc examples

kubemarine/procedures/upgrade.py
After https://github.com/Netcracker/KubeMarine/pull/495 kubeadm-config changes are not applied during upgrade procedure.
But it should be possible according this documentation: https://github.com/Netcracker/KubeMarine/blob/main/documentation/Maintenance.md#custom-settings-preservation-for-system-service
* Returned task, that was excluded from upgrade procedure.
**TestCase 1**
Steps:
1. Run `kubemarine install` task;
3. Override some parameter (e.g. `goaway-chance`) in cluster.yaml;
4. Run `kubemarine upgrade` task;
5. Get `kubeadm-config` from cluster;
Results:
| …
=> [CPDEV-96588] - apply kubeadm-config during upgrade

README.md, documentation/Installation.md, documentation/Maintenance.md
* Some essential statements about maintenance are not reflected in documentation.
* Added note about manual reconfiguring of a kubeadm cluster.
* Update MG, IG, README.
=> [PSUPCLPL-14309] Maintenance guide update

documentation/Installation.md, kubemarine/keepalived.py, kubemarine/procedures/install.py, kubemarine/resources/configurations/defaults.yaml, kubemarine/resources/schemas/definitions/services/loadbalancer.json, kubemarine/templates/keepalived.conf.j2, test/unit/test_keepalived.py
Now it's not possible to provide additional parameters for keepalived configuration except vrrp_ips.
But in fact, user should sometimes specify some custom parameters related to their environment, e.g.: https://serverfault.com/questions/821809/keepalived-send-gratuitous-arp-periodically/822004#822004
* Added new `services.loadbalancer.keepalived.global` section for `global_defs` keepalived parameters. Now following parameters are supported here:
* `vrrp_garp_master_refresh`;
* Modified keepalived config generation to support common parameters, not related to specific vrrp-ip;
* Supported user specified `config` or `config_file` as for haproxy configuration;
* Added documentation section with the list of parameters that are used for keepalived configuration;
Please describe …
=> [CPDEV-96114] add keepalived globals and custom template support

documentation/Maintenance.md, kubemarine/kubernetes/__init__.py, scripts/thirdparties/src/software/plugins.py, scripts/thirdparties/src/software/thirdparties.py, test/unit/test_upgrade.py, test/unit/tools/thirdparties/test_sync.py
* Support of granular 3rd party updates per specific Kubernetes version not touching the compatibility map of higher Kubernetes versions.
* Prohibit upgrade to not the latest supported patch version to avoid accidental downgrade of plugins or thirdparties.
* Added validation of `upgrade_plan` to allow upgrade only to the latest patch versions (either intermediate or target).
* Changed validation in `scripts/thirdparties/sync.py` to check that plugins are not downgraded only if upgrade is possible.
Upgrade to intermediate patch versions is no longer allowed.
**TestCase 1**
Granular upgrade of 3rd-parties.
Steps:
1. Embed new Kubernetes patch versions, and upgrade compatible plugins only for new Kubernetes versions.
2. Run `scripts/thirdparties/sync.py`
Results:
| ------ …
=> [CPDEV-96929] Support of granular 3rd party updates per specific Kubernetes version

documentation/internal/Hardening.md
* Clarify limitations and prerequisites for [Disable Anonymous Authentication for `kube-apiserver`](https://github.com/Netcracker/KubeMarine/blob/main/documentation/internal/Hardening.md#disable-anonymous-authentication-for-kube-apiserver).
**TestCase 1**
Install cluster, and then disable anonymous-auth for `kube-apiserver` according to guide [documentation/internal/Hardening.md#disable-anonymous-authentication-for-kube-apiserver](https://github.com/Netcracker/KubeMarine/blob/documentation/clarify_hardening_anonymous_auth/documentation/internal/Hardening.md#disable-anonymous-authentication-for-kube-apiserver)
**TestCase 2**
Perform maintenance procedures: upgrade, add/remove nodes taking into account [documentation/internal/Hardening.md#limitations](https://github.com/Netcracker/KubeMarine …
=> [CPREQ-8436] Clarify documentation Hardening.md: Disable Anonymous Authentication for kube-apiserver

kubemarine/thirdparties.py
Plugins which do not have `installation.procedures` cause upgrade failures
```
File "/usr/local/lib/python3.12/site-packages/kubemarine/thirdparties.py", line 418, in <genexpr>
for plugin_procedure in plugin_configs['installation']['procedures']
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'procedures'
```
Set keys `installation` and `installation.procedures` as optional, allowing empty values.
**TestCase 1**
Steps:
1. Add a custom plugins which does not have `installation.procedures` sections, run `upgrade`
Results:
| Upgrade fails on thirdparties  | Upgrade continues |
=> Allow plugins without installation procedures

kubemarine/kubernetes/__init__.py
There was a typo in the name of the file with scheduler's patch: `kube-scheduler_json.json` instead of `kube-scheduler+json.json`
The typo is fixed.
Deploy kubernetes with some kube-scheduler's customization, for example:
```
service:
kubeadm_patches:
scheduler:
- groups: [control-plane]
patch:
log-flush-frequency duration: 20s 
```
ER: kube-scheduler's manifest at the master nodes contains the new `log-flush-frequency duration` value.
=> Fix scheduler's patch name

documentation/Installation.md
There is some misunderstanding among users about the logic of `services.etc_hosts` and `services.coredns.configmap.Hosts` usage.
PSUPCLPL-14594
Installation guide is updated.
Not applicable
Not applicable.
=> [PSUPCLPL-14594] Update IN with warnings about etc_hosts

pyproject.toml
* If Kubemarine is run from sources and dump/ directory is created, attempt to build the package fails with
`Multiple top-level packages discovered in a flat-layout: ['dump', 'kubemarine']`
* Disable package automatic discovery by explicitly specifying where to search the packages in.
**TestCase 1**
Steps:
1. Run Kubemarine from sources
2. Install package from sources using `pip install .`
Results:
| Multiple top-level packages discovered in a flat-layout: ['dump', 'kubemarine'] | Package is built successfully |
=> Disable package automatic discovery of setuptools

kubemarine/procedures/migrate_kubemarine.py, kubemarine/resources/scripts/check_url_availability.py, kubemarine/resources/scripts/simple_port_client.py, kubemarine/resources/scripts/simple_port_listener.py, scripts/ci/build_binary.py
* `kubemarine migrate_kubemarine` fails with `NameError: name 'exit' is not defined` if run as executable file.
Fixes #612
* Avoid using of interactive constants from site module. https://docs.python.org/3/library/constants.html#constants-added-by-the-site-module
**TestCase 1**
Steps:
1. Run `kubemarine migrate_kubemarine --list` using Kubemarine v0.27.0 executable.
Results:
| NameError: name 'exit' is not defined | Prints "No patches available." |
=> Avoid interactive constants (exit) from site module

kubemarine/resources/scripts/check_url_availability.py
If user specify credentials for thirdparties in url, `check_iaas` can not check availability for them, because `urllib` package does not support user-info fields in url: https://bugs.python.org/issue34628
Modified `check_url_availability` script to extract credentials from url and apply them using official authorization mechanism.
**TestCase 1**: with python3
- Hardware: 
- OS: ubuntu or another OS with python3 installed
- Inventory: some thirdparties sources use secure registries
Steps:
1. Run `check_iaas`
Results:
| `software.thirdparties.availability` fails for secured thirdparties with `nonnumeric port` exception | `software.thirdparties.availability` finishes successfully |
**TestCase 1**: with python2
Test …
=> [CPDEV-98652] - parse url and provide creds as header in check_url_availability script

kubemarine/core/defaults.py, kubemarine/core/resources.py, kubemarine/kubernetes/__init__.py, test/unit/test_defaults.py
If source inventory contains blank values for some properties, they override defaults and then can be deleted during enrichment. Finalized inventory does not contain blank values for these properties. If it is used as a source inventory, the properties no longer override the defaults.
Added inventory finalization function that return blank overridden values to the finalized inventory.
**TestCase 1**
Steps:
1. Configure inventory
```yaml
services:
sysctl:
net.netfilter.nf_conntrack_max: ''
kubeadm_kube-proxy:
conntrack:
min: ''
```
2. Install cluster v1.29.1
3. Check `sysctl -a | grep net.netfilter.nf_conntrack_max`
ER: The property is set by kube-proxy to some default != 1000000.
4. Install new cluster using finalized inventory from step 2
5. Check `sysctl -a | grep …
=> Finalized inventory loses overridden blank strings

kubemarine/jinja.py, kubemarine/resources/configurations/defaults.yaml, test/unit/plugins/test_calico.py
* Kubemarine does not wait for healthy Calico Typha deployment and pods.
* Added calico-typha to the list for expect in defaults.yaml.
* Fix bug in is_true, is_false jinja filters for boolean values.
**TestCase 1**
Steps:
1. Enable Calico Typha in All-in-One scheme, and install the cluster.
Results:
| Cluster is installed successfully | Installation is failed because one of pods is in Pending state. |
test_calico.py - added tests for expect procedure enrichment if Calico Typha is enabled/disabled.
=> [CPDEV-98878] Expect calico-typha pods and deployment if enabled

kubemarine/core/resources.py, kubemarine/demo.py, kubemarine/procedures/do.py, test/unit/plugins/test_template.py, test/unit/test_do.py, test/unit/test_group.py
* After #577 `kubemarine do` fails with "KeyError: 'dump_location'"
* After #38 `do --no_stream` no longer prints output.
* Added missed keys to `do.create_context()`.
* If `--no_stream`, use print() instead of logger.debug().
**TestCase 1**
Steps:
1. Run `kubemarine do --no-stream -- whoami`
Results:
| Error: "KeyError: 'dump_location'" | Prints formatted output. |
test_do.py - new tests to cover `do` procedure.
=> Procedure `do` does not work

kubemarine/procedures/check_paas.py
The modification enhances the formatting of messages appended to the bad_results list within the check_packages_versions function. 
* 
https://tms.netcracker.com/browse/CPREQ-8729
The solution involves adjusting the format of the appended message to the bad_results list.
* 
**TestCase 1**
Steps:
1. Upgrade the containerd version from 1.6.* to 1.7.*
2. Run K=kubemarine check_paas
Results:
| Check the presence and correctness of the version of the following packages on the system: ['containerd=1.7.2-0ubuntu1~20.04.1'] | Check the presence and correctness of the version of the following packages on the system: ['containerd=1.6.* (Actual version: containerd=1.7.2-0ubuntu1~20.04.1, Expected package version: containerd=1.6.)']
|
Indicate …
=> [CPREQ-8729] Improve paas_check_detected_incorrect_packages_versions_explanation

kubemarine/kubernetes/__init__.py, kubemarine/kubernetes/components.py, kubemarine/patches/__init__.py, kubemarine/patches/patch_kubelet_configmap.py
Default value of resolvConf is uploaded to kubelet-config ConfigMap by kubeadm.
This causes problems in migration of operating systems, because resolvConf is taken from the ConfigMap,
while it should be different on different OS.
Fixes #586
If resolvConf is not redefined in the inventory, remove it from kubelet-config ConfigMap
* during `kubeadm init` of the first control plane.
* during `kubemarine reconfigure`
* in `services.kubelet.configuration` PaaS check when generating the CM for comparison.
Run `kubemarine migrate_kubemarine --force-apply kubelet_resolvConf`
**TestCase 1**
Migrate from Ubuntu 22.04 to RHEL9.
Steps:
1. Install cluster on Ubuntu 22.04.
2. Add node on RHEL9.
Results:
| Node is not joined. journalctl for kubelet contains error …
=> [CPDEV-98822] Remove default resolvConf from kubelet-config ConfigMap

documentation/Troubleshooting.md, kubemarine/core/errors.py, kubemarine/core/executor.py, kubemarine/core/group.py, test/unit/core/test_executor.py
* If `concurrent.futures` timeout occures, RemoteExecutor tries to join nodes gracefully and becomes stuck as the remote command is not killed. This was broken after #468 when we stopped passing timeout to fabric's `Connection.run|sudo`
* Timeout for `Connection.run|sudo` is returned.
* Implement parsing of output if timeout occures for merged commands.
* Remove timeout for `concurrent.futures` because it does not help to stop the command, but hides what command was timed out and what its stdout and stderr were.
* No longer try to use timeout for get/put operations.
**TestCase 1**
Steps:
1. Run `kubemarine do -- sleep 3600`
Results:
| "Action took too long to complete and timed out" after **1 hour** | "Command did not complete within 2700 seconds! …
=> [CPDEV-98972] Kubemarine process is stuck if remote command is stuck

documentation/Kubecheck.md, kubemarine/procedures/check_iaas.py
* `nosuid` mount option affects files capabilities, that makes impossible to use some features of containers
* Implement new task into `check_iaas` procedure
Not applicable
**TestCase 1**
Verify if the check is working for `containerd` CRI
- Hardware: 4CPU/8GB
- OS: Ubuntu 22.04/CentOS 7/RHEL8
- Inventory: AllinOne
Steps:
1. Prepare node without `nosuid` mount option for filesystem where `containerd` root directory is located
2. Run `check_iaas` procedure with `--tasks="system.fs_mount_options"` option
3. Prepare node with `nosuid` mount option for filesystem where `containerd` root directory is located (`/var/lib/containerd` or `/var/lib` or `/var` could be mounted with the `nosuid` option, if the `containerd` root is default)
4. Run `check_iaas` procedure with …
=> [PSUPCLPL-14914] FS mount options check

kubemarine/kubernetes/__init__.py
* After upgrade from v1.25.7 to v1.26.11 on Ubuntu 22.04, `check_paas` fails on task `services.kubelet.configuration`
* The reason is because kubelet-config ConfigMap can be overridden during `kubeadm apply`, and `resolvConf` is reset to the default one. We are not ok with default since #619
* Patch kubelet-config ConfigMap during upgrade.
**TestCase 1**
Steps:
1. Install cluster v1.25.7
2. Upgrade to  v1.26.1
3. Run `check_paas`
Results:
| kubelet-config ConfigMap is not consistent with services.kubeadm_kubelet section | Check is passed |
=> [CPDEV-99413] Patch kubelet-config ConfigMap during upgrade

kubemarine/core/flow.py, kubemarine/core/resources.py, kubemarine/demo.py, kubemarine/procedures/do.py, test/unit/core/test_run_actions.py, test/unit/test_do.py, test/unit/utils.py
* After #621 cluster_finalized.yaml is not longer dumped in current working directory, if `--disable-dump --without-act` args are used simultaneously.
* Revert the behavior. Introduce `context['make_finalized_inventory']` that manages if the cluster_finalized.yaml should be collected and dumped, that is `True` for all procedures except `do`.
**TestCase 1**
Steps:
1. Run `kubemarine install --disable-dump --without-act`
Results:
| cluster_finalized.yaml is not collected neither dumped | cluster_finalized.yaml is collected and dumped in current working directory only |
test_run_actions.py - add test to cover cluster_finalized.yaml with the combination of options.
=> [CPDEV-100505] Always dump finalized inventory for all procedures except `do`

kubemarine/patches/__init__.py, kubemarine/patches/strong_cipher_suits_for_kubelet.py, kubemarine/resources/configurations/defaults.yaml
These cipher suites are configuring the kubelet to support a selection of strong and secure cryptographic algorithms for secure communication over TLS (Transport Layer Security).
* 
[CPDEV-98472](https://tms.netcracker.com/browse/CPDEV-98472)
1. Add tls-cipher-suits by default for new cluster installation.
2. Add a patch to reconfigure kubelet for already installed cluster
**TestCase 1**
- OS: Ubuntu-20.04
Steps:
1. Installed a miniha cluster
2. Installed kube-bench to make KubeMarine CIS aligned. 
3. Run scan using command - kube-bench and check for identifier **4.2.12**.
Results:
| Result used to be Warning | Result shows Pass |
**TestCase 2**
Apply the patch for the old clusters where kubelet Cryptographic …
=> [CPDEV-98472]-Enabling_strong_crypto_support_by_default_for_kubelet

kubemarine/procedures/check_iaas.py, kubemarine/procedures/check_paas.py, kubemarine/resources/scripts/check_url_availability.py, kubemarine/thirdparties.py
* Install and check thirdparties skipping SSL verification.
* Added `curl -k` option during install.
* Disable SSL verification in `check_url_availability.py` using custom SSL context in HTTPSHandler.
* `software.thirdparties.availability` check now respects probably not yet installed resolv.conf.
**TestCase 1**
- OS: Ubuntu 22.04 / Centos 7
- Inventory: `services.thirdparties.source` with self-signed certificate.
Steps:
1. Install the cluster.
Results:
| Installation fails | Installation succeeds |
**TestCase 2**
- OS: Ubuntu 22.04 / Centos 7
- Inventory: `services.thirdparties.source` with self-signed certificate.
Steps:
1. Run `check_iaas --tasks software.thirdparties.availability`
Results:
| Before | After …
=> [CPDEV-100414] Install and check thirdparties skipping SSL verification

documentation/Maintenance.md
When a balancer node is added with `add_node`, keepalived is not installed/configured at the newly added node in case of `vrrp_ip` section is already configured in the `cluster.yaml`. 
Maintenance guide omits this case.
PSUPCLPL-15188
Update MG: a note is added to the `add_node` procedure description, covering the case when `vrrp_ips` section exists in the `cluster.yaml` and a balancer node is being added.
-
Deploy a k8s cluster with 1 or more balancer nodes and the vrrp_ip address.
Run `add_node` procedure to add a node with the `balancer` role configuring procedure.yaml according to the [documentation](https://github.com/Netcracker/KubeMarine/blob/PSUPCLPL-15188_doc_update_on_add_lb_node/documentation/Maintenance.md#configuring-add-node-procedure).
**ER**: the new node …
=> [PSUPCLPL-15188] Add a note about balancers to add_node procedure to MG

documentation/Installation.md, kubemarine/resources/configurations/globals.yaml
* To add support for k8s installation on servers running on operation system Rocky Linux 9.3 using kubemarine
* Add Rocky Linux's latest version i.e. `9.3` in the supported OS family in `globals.yaml` file 
**TestCase 1**
- Hardware: Opensatck VMs
- OS: RockyLinux 9.3
- Inventory: miniHA scheme for k8s cluster
Steps:
1. Kubemarine check_iaas
AR: Check_iaas succeeded
2. Kubemarine install
AR: Installation succeeded
3. Kubemarine check_paas
AR: check_paas succeeded
4. kubemarine upgrade
AR: Kubernetes version upgraded successfully to the k8s version provided in upgrade plan through `procedure.yaml` as below
```
upgrade_plan:
- v1.29.1
```
=> [CPREQ-9137] - RockyLinux 9.3 support for Kubemarine

kubemarine/kubernetes/__init__.py
The issue is in the drain_nodes function where the condition if node_name in stdout incorrectly evaluates to true if node_name is a substring of one or more active node names in the cluster.
* 
Fixes # ([PSUPCLPL-15213](https://tms.netcracker.com/browse/PSUPCLPL-15213))
To address this issue, modified the condition to ensure that it checks for exact matches rather than substring matches. We can achieve this by splitting the stdout into lines and then checking if node_name exactly matches any line in the output.
* 
**TestCase 1**
Steps:
1. Run add node procedure with a node name which will be a substring of one or more active node names
Example - There is already a node in the cluster with name **test-worker-3-10** and then try to add a new node with name …
=> [PSUPCLPL-15213]-Node_not_found_error_when_running_add_node_procedure

documentation/Maintenance.md, kubemarine/core/cluster.py, kubemarine/coredns.py, kubemarine/packages.py, kubemarine/procedures/install.py, test/unit/core/test_flow.py
It is not possible to run add_node and remove_node if there are unavailable workers in cluster.yaml.
The accessibility check will be performed only for control-plains, balancers and new nodes.
The same for `prepare.check.sudoer` task
`coredns-configmap.yaml` and `coredns-deployment-patch.yaml` will save only on control-plains
Excluded offline nodes for the `cache_packages` task
Updating etc_hosts will not be executed for offline nodes during the `prepare.dns.etc_hosts` task
Steps:
1. Stop worker node in the cluster
2.  Create new VM and add the following entries to `/etc/hosts` on it:
```
<cluster_ip>                 <cluster_name> control-plain
<internal_new_node_ip>       <new_node_name>
```
3. Run  `add_node` for new VM with `--exclude=prepare.dns.etc_hosts`
4. Run  `remove_node` for …
=> [CPDEV-95355] add_node and remove_node if there are notready workers

kubemarine/kubernetes/__init__.py, kubemarine/procedures/upgrade.py, test/unit/test_upgrade.py
* After #627 upgrade sometimes fail during call to `components.patch_kubelet_configmap`. Reproduced on rhel 9.2, upgrade v1.26.11 -> v1.27.8, full HA.
* The reason is because `kubeadm apply` updates kubelet-config ConfigMap using not yet upgraded node with working control plane components, while `components.patch_kubelet_configmap` may randomly go through node with not yet working kube-apiserver.
* Move `components.patch_kubelet_configmap` after waiting for readiness of control plane pods.
**TestCase 1**
- OS: rhel 9.2
- Inventory: Kubernetes v1.26.11, 1 balancer, 3 control-plane & worker nodes.
Steps:
1. Install the cluster
2. Upgrade to v1.27.8
Results:
| Upgrade sometimes fail on `kubernetes` task | Upgrade is successful. |
=> [CPDEV-100496] Ensure to use kubectl after wait for first control plane pods

kubemarine/patches/__init__.py, kubemarine/patches/reinstall_etcdctl_thirdparty.py, kubemarine/procedures/restore.py, kubemarine/resources/scripts/etcdctl.sh
During restore procedure user can override etcd image with `restore_plan.etcd.image` parameter. But in real, this image is applied only to etcd container, but not in etcdctl.
As result etcdctl gets the image from the manifests, pulls it and restores snapshot, but when etcd runs then, it fails with image not found exception.
* Added the possibility to override the image (and other etcd parameters in etcdctl);
* Fixed `etcdctl restore snapshot` command in `restore` procedure with custom etcd image/certs/mounts, that is calculated before;
* Provided the patch, that uploads the new etcdctl thirdparty on the nodes;
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test …
=> [CPDEV-101094] possibility to override etcdctl parameters

.github/workflows/ci.yaml
* Unit tests on macos-latest fail with "Error: The version '3.7' with architecture 'arm64' was not found for macOS 14.4.1."
* Use macos-13
=> Fix unit tests on macos

pyproject.toml, scripts/ci/build_binary.py
* Unpin and update ruamel.yaml dependency
* Exclude dependency on ruamel.yaml.clib to fix binary build for macos11-arm64
Fixes #439
=> Update ruamel.yaml dependency

kubemarine/procedures/check_iaas.py, kubemarine/resources/scripts/source/ipip_check/ipip_check.go
* The `network.ipip_connectivity` task in `check_iaas` could return incorrect results due to IaaS level firewall rules. For instance, in OpenStack set of `Iptables` rules that implements the `Security Group`. That `Iptables` rules allow the `ESTABLISHED` and `RELATED` packets which leads to the following case. IPIP packets moving from VM-1 to VM-2 are blocked, but the IPIP packets from VM-2 to VM-1 are allowed as they look like `RELATED` packets whereas, IPIP traffic is not allowed in `Security Group` at all for VM-1 and VM-2.
* In this case, the only way to check the IPIP connectivity in cluster is to avoid IPIP packets movement from VM-1 to VM-2 and vice versa. Therefore, VM-1 must send packets to VM-2 and VM-2 to VM-3 and VM-3 must send packets to VM-1 (if there are three nodes in the …
=> [PSUPCLPL-15272] IPIP connectivity check rework

documentation/Installation.md, kubemarine/core/defaults.py, kubemarine/core/errors.py, kubemarine/core/proxytypes.py, kubemarine/core/resources.py, kubemarine/jinja.py, kubemarine/plugins/__init__.py, kubemarine/procedures/check_iaas.py, kubemarine/resources/configurations/defaults.yaml, test/unit/core/test_cluster.py, test/unit/core/test_jinja.py, test/unit/core/test_run_actions.py, test/unit/plugins/test_template.py, test/unit/test_coredns.py, test/unit/test_defaults.py, test/unit/test_k8s_cert.py, test/unit/test_migrate_kubemarine.py, test/unit/utils.py
* We have own implementation of compilation of jinja templates with both iterative and recursive compilation.
* Due to iterative compilation, some default features of jinja do not work.
* Recursive compilation is supported only for some custom [filters](https://jinja.palletsprojects.com/en/3.0.x/templates/#filters), but not for the jinja's default ones.
* To use primitive values (like plugins.install) inside templates we have to use filters like `is_true`, `is_false`.
* Finally, there is no control over the compilation process
* May complicate development (e.g. changing of inventory format)
* Does not handle infinite recursion.
* Instead of iterative and recursive compilation, only recursive compilation is left.
* In recursive compilation, any access to the inventory sections inside …
=> [CPDEV-101596] Rework of inventory compilation

documentation/Installation.md, documentation/Maintenance.md, kubemarine/apparmor.py, kubemarine/core/cluster.py, kubemarine/core/group.py, kubemarine/core/inventory.py, kubemarine/core/resources.py, kubemarine/kubernetes/__init__.py, kubemarine/procedures/install.py, kubemarine/procedures/reconfigure.py, kubemarine/resources/configurations/defaults.yaml, kubemarine/resources/schemas/definitions/patch.json, kubemarine/resources/schemas/definitions/services/kubeadm_patches.json, kubemarine/resources/schemas/reconfigure.json, kubemarine/selinux.py, kubemarine/sysctl.py, kubemarine/system.py, test/unit/test_reconfigure.py
* If maxPods or podPidsLimit are reconfigured in `services.kubeadm_patches.kubelet`,
the related kernel parameter kernel.pid_max is not reconfigured.
* PaaS check fails because the parameter value is unexpected.
* The problem appeared after #639 after which calculated kernel.pid_max started to take into account kubeadm patches.
* Support to reconfigure `services.sysctl` and `patches` using `reconfigure` procedure.
* Added task `prepare.system.sysctl`.
* In comparison to the installation procedure, the task does not trigger reboot.
* `services.sysctl` is merged with the main inventory, and `patches` can only be appended.
* Implemented detecting of changes in the inventory in `prepare.system.sysctl` and `deploy.kubernetes.reconfigure` tasks.
* If maxPods or podPidsLimit are changed for …
=> [CPDEV-101285] Reconfigure sysctl

ci/extended_cluster.yaml, kubemarine/patches/__init__.py, kubemarine/patches/p1_calico_typha_schedule_control_planes.py, kubemarine/plugins/builtin.py, kubemarine/plugins/calico.py, kubemarine/plugins/manifest.py, kubemarine/resources/configurations/defaults.yaml, test/unit/plugins/test_calico.py, test/unit/test_defaults.py
* If Calico Typha is enabled in All-in-One, installation fails.
* This is caused by #618 after which we started to expect Typha deployment.
* Calico Typha is not scheduled on control-planes for old Kubernetes versions.
* Scale Typha replicas to 1 if it is enabled in schemes with 1 Kubernetes node.
* If 2nd Kubernetes node is added, scale replicas to 2 and redeploy `calico` plugin.
* Add default tolerations to schedule Calico Typha on all nodes for old Kubernetes versions.
Run `kubemarine migrate_kubemarine --force-apply calico_typha_schedule_control_planes`
**TestCase 1**
Enable Calico Typha in All-in-One.
Steps:
1. Set `plugins.calico.typha.enabled` to True in All-in-One and install the cluster.
Results:
| Installation fails | Installation succeeds …
=> [CPDEV-98973] Scale Typha replicas to 1 in All-in-One

kubemarine/kubernetes/__init__.py
During upgrade procedure we create special temporary file with node versions: `/etc/kubernetes/nodes-k8s-versions.txt`.
This file is needed to continue from the same step after failed upgrade: https://github.com/Netcracker/KubeMarine/blob/main/documentation/Maintenance.md#nodes-saved-versions-before-upgrade
This file is created with such complex command: https://github.com/Netcracker/KubeMarine/blob/v0.30.0/kubemarine/kubernetes/__init__.py#L1002
But if something went wrong, when kubemarine calls `kubectl get nodes` command (e.g. etcd restarts for some reason), no exceptions will be called and empty `/etc/kubernetes/nodes-k8s-versions.txt` will be created.
After that the exception appears in the next parsing of this file:
```
2024-05-16 15:44:30.854 +0300 INFO *** TASK prepull_images *** …
```
=> [CPDEV-101898] - do not create empty /etc/kubernetes/nodes-k8s-versions.txt file

scripts/thirdparties/src/software/kubernetes_images.py, scripts/thirdparties/src/software/packages.py, test/unit/tools/thirdparties/stub.py, test/unit/tools/thirdparties/test_sync.py
* If some kubernetes image version downgrades in the compatibility map, it may still not downgrade during Kubernetes upgrade.
* This leads to inconsistency of expected and actual versions, PaaS check may fail, and behavior of `kubemarine add_node`, `kubemarine reconfigure` is undefined.
* Validate that kubernetes images are not downgraded for allowed upgrade cases.
* The PR can be merged once the problem with downgrade of etcd for v1.28.8 -> v1.29.1 is solved.
**TestCase 1**
Steps:
1. Run `scripts/thirdparties/sync.py`
ER: Until v1.29.1 is the latest patch version for Kubernetes v1.29, the tools fails.
test_sync.py - cover new case of validation
=> [CPDEV-100884] Validate that kubernetes images are not downgraded

documentation/Troubleshooting.md, kubemarine/core/errors.py, kubemarine/core/resources.py, kubemarine/kubernetes/__init__.py, test/unit/core/test_cluster.py, test/unit/core/test_flow.py, test/unit/test_defaults.py, test/unit/test_do.py, test/unit/test_inventory.py
* If no nodes with `control-plane` role are provided, Kubemarine fails with internal error.
* At least one control-plane node is necessary even for connection-only enrichment
* choose default node in `do` procedure
* preserve information about the procedure run.
* In contrast, it is potentially possible to install the cluster with the only `control-plane` node for dev aims.
* In particular, this allows to rebuild the only worker node using remove & add node while temporarily persisting only control planes.
* Raise exception if no control planes are specified in the inventory.
* Allow clusters without workers.
**TestCase 1**
Rebuild the only worker node using remove & add node.
Steps:
1. Install the cluster with 1 worker and 1 control-plane.
2. Remove the only worker.
Results:
| Before | …
=> [CPDEV-101682] Support single control plane cluster

documentation/Installation.md
* In some cases intermediate certificate should be specified in `nginx-ingress-controller` plugin. 
* Documentation update
=> [PSUPCLPL-15568] Certificate specification

kubemarine/patches/__init__.py, kubemarine/patches/p3_reconfigure_audit.py
* In #665 default audit policy configuration has changed, but patch was not written.
* Implemented patch the similar way as in #516
Run `kubemarine migrate_kubemarine --force-apply reconfigure_audit`.
**TestCase 1**
Steps:
1. Install cluster using **old** Kubemarine version.
Next steps should be performed using **new** Kubemarine version.
2. Run `check_paas`.
ER: kubernetes.audit.policy should fail.
3. Run `kubemarine migrate_kubemarine --force-apply reconfigure_audit`.
4. Run `check_paas`.
ER: kubernetes.audit.policy should succeed.
=> [CPDEV-102476] Implement patch that reconfigures Kubernetes audit

kubemarine/etcd.py, kubemarine/procedures/check_paas.py, kubemarine/resources/configurations/globals.yaml
* `check_paas --tasks etcd.health_status` works long due to sleep for 30 seconds.
* Remove sleep. Use warn=True to handle potential errors.
**TestCase 1**
Steps:
1. Run `check_paas --tasks etcd.health_status`.
Results:
| Works more than 30 seconds | Works 30 seconds less |
=> [CPDEV-103323] No initial timeout for etcd check

kubemarine/core/connections.py, kubemarine/core/executor.py, kubemarine/core/group.py, kubemarine/core/utils.py, kubemarine/demo.py, kubemarine/kubernetes/secrets.py, kubemarine/plugins/__init__.py, kubemarine/procedures/check_iaas.py, kubemarine/procedures/check_paas.py, kubemarine/procedures/restore.py, kubemarine/resources/configurations/globals.yaml, kubemarine/thirdparties.py
* Support calculating of sha1 for `Connection.put()` of in memory StringIO buffer.
* Added option `NodeGroup.put(compare_hashes=True)` to specify if sha1 of remote and local files should be compared.
* The option is set to `False` in all cases when we do not expect existence of remote file, or expect its sha1 being always different.
* Added check of sha1 for thirdparties provided as scripts (etcdctl.sh).
* `check_iaas --tasks network.ipip_connectivity` now copies ipip_check binary only if is not copied yet or not actual.
* Fail connect attempts early in case of not a connection-related exceptions.
* fabric's Connection is now instantiated with channel_timeout=10 (default) to recover from problems with SSH (like in comment https://github.com/Netcracker/KubeMarine/pull/463#discussion_r124505 …
=> [CPDEV-103189] Different improvements in SSH connections usage

.github/workflows/ci.yaml
macos11 github runners stuck because of https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/
* move build process to macos12
**TestCase 1**
- Hardware: 
- OS: 
- Inventory: 
Steps:
1. 
Results:
|  |  |
=> build process macos11 to macos12 migration due to macos11 deprecation

kubemarine/core/executor.py, pyproject.toml
We have differences between types packages versions for mypy and real packages, that can follow issues like recently found one:  
We have `jsonschema=4.22.*` requirement and  `types-jsonschema==4.*` one for mypy. It worked normally, until `jsonschema=4.23.0` was released. This version contains more strict changes in data types. So we still install `jsonschema=4.22.*` as before, but when we run mypy check in CI, `types-jsonschema==4.23.0` is installed and check fails because of differences in between  types in our code and expected ones.
* Fixed types package versions to be compatible with real packages versions;
* Removed `types-invoke` package, because we use `invoke-2.2.*` that contains types information itself. From [official package …
=> Mypy fixes

kubemarine/procedures/upgrade.py
After Kubernetes Upgrade procedure check_paas indicates inconsistencies in the IP address management (IPAM) system used by Calico in Kubernetes cluster. Specifically, it identifies the following problems:
1. IPs with missing handles: These are IP addresses that are allocated but do not have corresponding handles in the IPAM system.
2. Handles with no matching IPs: These are handles in the IPAM system that do not have corresponding IP addresses allocated to them. 
* 
Added a function(release_calico_leaked_ips) in the upgrade procedure. This function should parse the output of the calicoctl ipam check --show-problem-ips command, identify the problematic IPs and handles, and release them automatically.
* 
**TestCase 1**
Steps:
1. Run kubemarine upgrade
2. Run kubemarine check_paas
Results:
| …
=> [CPDEV-93296]PAAS_check_failed_after_procedure_Kubernetes_upgrade

documentation/Installation.md, kubemarine/procedures/install.py, kubemarine/resources/configurations/defaults.yaml, kubemarine/resources/schemas/definitions/globals.json
When one or more nodes are unavailable, `add_node`, `remove_node` procedures have to be run with `prepare.dns.etc_hosts` or `update.etc_hosts` task skipped (see [PR](https://github.com/Netcracker/KubeMarine/pull/628)).
If after that you try to add another node, `add_node` fails with error like 
```
Temporary failure in name resolution': ['some_node_fqdn']}
```
CPDEV-103936
1. New boolean parameter `globals.ignore_unavailable_nodes_for_etchosts_update` is added to cluster.yaml with default value False.
`system_prepare_dns_etc_hosts` is adjusted to work as previously if `globals.ignore_unavailable_nodes_for_etchosts_update= false` and update /etc/hosts only at the available nodes if it's set to True.
2. IN is updated with description of new variable.
**TestCase 1**
step 1) …
=> [CPDEV-103936] Fix prepare_dns_etc_hosts for work with unavailable nodes

kubemarine/core/connections.py
When node s rebooted, sometimes an eof error ocurrs, that fails kubemarine process. This floating issue occurs in case, if this node has opened sftp connection (it's opened on put to node/get from node operations), that nexpectedly closes from the node side, that can follow eof error, when kubemarine tries to close it from its side. Such behavior was detected on rhel 9 nodes:
```
2024-07-03 21:48:02.062 +0400   File "/usr/local/lib/python3.12/site-packages/kubemarine/core/flow.py", line 57, in run_flow
2024-07-03 21:48:02.062 +0400     self._run(resources)
2024-07-03 21:48:02.062 +0400   File "/usr/local/lib/python3.12/site-packages/kubemarine/core/flow.py", line 88, in _run
2024-07-03 21:48:02.062 +0400     run_actions(resources, self._actions)
2024-07-03 21:48:02.062 +0400   File …
```
=> [CPDEV-103824] - caught sftp eof error during reboot

kubemarine/procedures/backup.py
When doing the following sequence of action:
- backup
- restore
- backup
the last backup fails at RHEL hosts.
Out of the box RHEL has fs.protected_regular kernel variable set to 1 which means prohibiting O_CREAT open on regular files that we don’t own in world writable sticky directories (which the /tmp folder is), unless they are owned by the owner of the directory.
After the restore procedure the /tmp/kubemarine-backup.tar.gz file is left in /tmp folder, so the second backup procedure tries to update an existing file and fails.
Actually, Ubuntu 20.04 and 22.04 have fs.protected_regular=2 which means the same as 1, but also applies to group writable sticky directories, so the issue must be reproduced there too. Centos 7 doesn't have this variable and doesn't have such an issue.
`Restore` …
=> [CPDEV-101420] Fix failure of second backup after restore

.github/workflows/integration_tests.yaml, .github/workflows/tests.yaml, Dockerfile, documentation/Kubecheck.md, kubemarine/kubernetes/__init__.py, kubemarine/procedures/check_paas.py, kubemarine/resources/configurations/compatibility/kubernetes_versions.yaml, scripts/thirdparties/src/run.py, scripts/thirdparties/src/software/defaults.py, scripts/thirdparties/sync.py, test/unit/tools/thirdparties/stub.py, test/unit/tools/thirdparties/test_sync.py
Kubernetes versions are excluded from support in kubemarine without any warnings (except mentions in release notes).
But user should plan your upgrade to a new version in advance, so should know when the version he is using becomes a deprecated version and will soon be disabled.
* Added version deprecation support in compatibility map:
* Reused `supported` field to mark version as deprecated;
* Fixed logs after `install`/`upgrade` procedures, warn if version is deprecated;
* Added new check-paas task, that checks, if version is deprecated;
* Kubernetes `1.26` is marked as deprecated;
* Added validation check for sync tool
* If default version does not exist in compatibility map (should be removed), sync tool fails with exception;
* Other fixes:
* Fixed docker build issue: fixed tags for …
=> [CPREQ-10003] - deprecated kuber version

documentation/Troubleshooting.md
Since we update OpenSSL by default when deploying a cluster with KubeMarine, a version incompatibility problem arises. OpenSSH was compiled with OpenSSL version 3.0.0 (30000070), and after the update we have version 3.2.0 (30200010) installed.
WA has been added to TG.
=> [CPDEV-102270] OpenSSH server issue WA has been added to TG.

kubemarine/cri/containerd.py
*   _containerd_ configuration procedure  doesn't wait that _containred_ daemon is healthy after restart. This may cause to issue when _containerd_ daemon is not ready yet and cri request fails.
Possible way to reproduce:
```
...
FATA[0000] validate service connection: validate CRI v1 runtime API for endpoint "unix:///run/containerd/containerd.sock": rpc error: code = Unknown desc = server is not initialized yet
```
* To add _containerd_ health check in _containerd_ configuration procedure using active polling with 10 sec timout
**TestCase 1**
Steps:
1. 
Results:
|  |  |
=> [CPDEV-106079] add containerd health check after restart

kubemarine/core/errors.py, kubemarine/plugins/__init__.py
If user uses remote url to install helm chart plugin, for some reasons unexpected content may return instead of zip/targz file.  
For example it can happens, if helm chart archive is stored in privated gitlab instance, that requires authorization. Without it gitlab redirects the request to sign-in page, so html content with 200 status code is returned.  
Now we fail with unexpected expression in kubemarine:
```
2024-10-31 08:32:57,855 CRITICAL FAILURE!
2024-10-31 08:32:57,855 CRITICAL TASK FAILED deploy.plugins
2024-10-31 08:32:57,855 CRITICAL KME0001: Unexpected exception
Traceback (most recent call last):
File "C:\Users\mame0719\Desktop\PaaS\github\KubeMarine\kubemarine\core\flow.py", line 382, in run_tasks_recursive
task(cluster)
File …
```
=> [CPDEV-107325] - add KME error if unexpected content is returned for helm chart

kubemarine/cri/containerd.py, kubemarine/kubernetes/__init__.py
During upgrade pcoderure kubemarine updates containerd configuration (and maybe containerd version) on nodes before upgrading kubernetes version on them using kubeadm command. But sometimes, containerd does not have time to start before the kubeadm command is launched, which is why the procedure fails. This is **floating** issue:
```
2024-11-14 07:32:47,829 DEBUG 'containerd' package upgrade is not required
2024-11-14 07:32:47,837 DEBUG Uploading containerd configuration to fullha-master2 node...
2024-11-14 07:32:47,838 DEBUG Uploading containerd registries configuration to /etc/containerd/certs.d on fullha-master2 node...
2024-11-14 07:32:47,840 DEBUG Restarting Containerd on fullha-master2 node...
2024-11-14 07:32:49,014 DEBUG Patching /var/lib/kubelet/kubeadm-flags.env on …
```
=> [CPDEV-107544] - wait containerd restart in upgrade procedure

documentation/Troubleshooting.md
Calico-node pods generate a lot of logs and consume a lot of resources that causes pod restart.
WA is provided in TG.
=> [PSUPCLPL-17043] Calico xdp issue TG update.

.github/workflows/ci.yaml, .github/workflows/integration_tests.yaml, kubemarine/kubernetes/components.py
* Gitlab actions are failing due Deprecated version (v3) of the artifact actions as starting for **30th January 2025**, v3 version of artifact actions has been deprecated.
* [CPDEV-110904]
* Updated version of artifact actions to **v4**
* Manual step 
=> [CPDEV-110904] Deprecated version (v3) of the artifact actions

.gitignore, kubemarine/kubernetes/__init__.py, kubemarine/kubernetes/components.py, kubemarine/procedures/check_paas.py, kubemarine/resources/configurations/compatibility/internal/kubernetes_images.yaml, kubemarine/resources/configurations/compatibility/internal/packages.yaml, kubemarine/resources/configurations/compatibility/internal/plugins.yaml, kubemarine/resources/configurations/compatibility/internal/thirdparties.yaml, kubemarine/resources/configurations/compatibility/kubernetes_versions.yaml
* New Kubernetes version v1.32.0 is available and we are going to add support for it in kubemarine
[CPDEV-110491](https://tms.netcracker.com/browse/CPDEV-110491)
*  Add support for v1.32.0
**TestCase 1**
* Run `kubemarine install` procedure for k8s version **v1.32.0**
- Hardware: Openshift
- OS: Ubuntu 22.04 LTS
- Inventory: MiniHA/FullHA/All-in-One
Results:
|  Failed to proceed inventory file.  KME0008: Specified Kubernetes version 'v1.32.0' - cannot be used!   | Successful installation of cluster with kubernetes version v1.32.0 |
=> [CPDEV-110491] - Add new Kubernetes version v1.32

documentation/Troubleshooting.md
* Common network issues should be described in documentation 
* Documentation update
=> Troubleshooting guide update

documentation/Troubleshooting.md
Updated the rest of the error codes(KME0006 to KME0014) in the TG from the info present in the errors.py file.
* 
=> Update TroubleshootingGuide.md according to unified Cloud Infra TG requirements

.github/workflows/pypi.yaml
* Deprecated version of `gh-action-pypi-publish` is causing failure for pypi package publishing 
* Update version for `gh-action-pypi-publish` to **v1.12.4**
=> Update version for gh-action-pypi-publish

documentation/Installation.md, kubemarine/kubernetes_accounts.py, kubemarine/patches/__init__.py, kubemarine/patches/configure_sa_issuer_discovery.py, kubemarine/resources/configurations/defaults.yaml, kubemarine/resources/schemas/definitions/rbac.json
Some applications do not support authenticated OIDC discovery endpoints, but Kubernetes by default enables authentication https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-issuer-discovery
Need to disable this authentication by default, but allow to enable it if needed
* added new boolean parameter `rbac.authenticated-issuer-discovery` which is set to `false` by default (disable authentication)
* `deploy.accounts` install task was extended to apply/delete CRB which allows unauthenticated users to access OIDC discovery endpoints
* added patch to apply new default on existing clusters
* added documentation
* `migrate_kubemarine` with patch `configure_sa_issuer_discovery`
**TestCase 1**
New KubeMarine version migration should enable …
=> Support unauthenticated OIDC discovery endpoint

Dockerfile
Need to update helm to fix vulnerability https://nvd.nist.gov/vuln/detail/CVE-2025-22871
Our helm version is affected, because it uses go 1.23.7.
* Update to helm v3.18.3, which uses go 1.24 where this vulnerability is fixed
=> Helm vulnerability fix

kubemarine/kubernetes/__init__.py, kubemarine/procedures/install.py, kubemarine/procedures/upgrade.py, kubemarine/thirdparties.py
During upgrade, if new kubelet version is installed on all nodes and then kubelet service is immediately restarted on all nodes, upgrade will fail, because a lot of pods in the cluster will become non-functional due to inconsistent kubelet/kubernetes version.
Overall, this is risky to upgrade kubelet globally on all nodes at the beginning of the upgrade, because upgrade may fail and cluster will be left in a fragile state with inconsistent kubelet.
As the least invasive fix, we could upgrade kubelet per-node, right after node draining:
* changed `install_all_thirdparties` task:
* now this task allows excluding thirdparty from upgrade
* fixed name typo
* during upgrade, kubelet is excluded from global thirdparties upgrade
* kubelet thirdparty is upgraded per-node during …
=> per-node kubelet upgrade

kubemarine/patches/__init__.py, kubemarine/patches/containerd_upgrade.py
Containerd was upgraded in https://github.com/Netcracker/KubeMarine/pull/735, but the related patch does not work, since it does not handle specific problems with iptables which occur during containerd 1.6 -> 1.7 upgrade (from ubuntu repositories)
* Patch from v0.37.0 was marked to have known issue and recommended to skip
* Added new patch for next KM release, which helps to upgrade containerd correctly
* This patch works only if it detects that some nodes have containerd package different from inventory version
* On problematic nodes, containerd upgrade is performed with caution:
* Node is drained first (best-effort)
* Kubelet is stopped
* Containerd pod sandboxes removed
* Required containerd version is installed
* Kubelet started, node uncordoned (with retries)
* For control-plane …
=> Containerd upgrade patch

kubemarine/patches/software_upgrade.yaml, kubemarine/resources/configurations/compatibility/internal/plugins.yaml, kubemarine/resources/configurations/compatibility/internal/thirdparties.yaml, kubemarine/resources/configurations/compatibility/kubernetes_versions.yaml
We do not support old k8s patch versions, users should upgrade to latest k8s patch versions. So calico update in old k8s patch versions is reverted to reduce support efforts
* Reverted calico image and calicoctl update for old k8s patch versions
* Removed old k8s patch versions from migrate patch (since there is nothing to migrate)
=> revert calico update for old k8s patch versions

documentation/Maintenance.md
Currently, some procedures are in general non-retriable with the same "procedure.yaml", which may be not obvious for users. Particularly:
* Upgrade is not retriable with the same "procedure.yaml" once it updates k8s version in "cluster.yaml".
* Add node is not retriable with the same "procedure.yaml" once it completes with any task
* Remove node is not retriable with the same "procedure.yaml" once it completes with any task
To retry such procedures, it is required to change "cluster.yaml" or "procedure.yaml" accordingly
* Added notes on non-retriable procedures
=> Add notes on non-retriable procedures

kubemarine/plugins/calico.py
Additional `stagedglobalnetworkpolicies` missing permissions for https://github.com/Netcracker/KubeMarine/pull/771
=> fix calico-apiserver permissions (for staged global network policies)
