Netcracker/KubeMarine

kubemarine/resources/configurations/globals.yaml, kubemarine/templates/plugins/calico-v3.24.yaml.j2
* Runtime error: invalid memory address or nil pointer dereference
* Add support new version Calicoctl on the 3.24.1
=> [PSUPCLPL-10685] Calico CNI panicked during ADD: runtime error: invalid memory address or nil pointer dereference

documentation/Installation.md, kubemarine/resources/configurations/globals.yaml
* You need to update Installation.md with new information about possible kubernetes images and plugins and edit sha sum kubelet
* Information about kubernetes version 1.23.11 and calico plugin version 3.24.1 has been added and update sha kubelet
=> [MANOPD-1] Update Installation.md and sha sum kubelet

README.md, bin/kubemarine, bin/kubemarine.cmd, build.sh, documentation/Installation.md, kubemarine/core/connections.py, kubemarine/core/group.py, kubemarine/core/log.py, kubemarine/demo.py, kubemarine/plugins/__init__.py, kubemarine/resources/configurations/globals.yaml, requirements_nt.txt
* Kubemarine CLI installation does not work on Windows.
* Some features of Kubemarine does not work when deploying from Windows.
Fixes #108 
* Added separate requirements file `requirements_nt.txt` with Windows specific 3rd-parties.
* Added `bin/kubemarine.cmd` to simplify running of Kubemarine using CLI.
* Ansible is now explicitly not supported on Windows.
* Added helm plugin support.
* Removed requirement to install OpenSSL on deployer. Python native library `hashlib` is used instead.
* Corresponding changes in [Kubemarine CLI Installation](https://github.com/Netcracker/KubeMarine/blob/feature/run_from_windows/README.md#kubemarine-cli-installation) guide and [install procedure](https://github.com/Netcracker/KubeMarine/blob/feature/run_from_windows/documentation/Installation.md) guide. …
=> MANOPD-74208 Support deploy from windows

documentation/Installation.md
Update Installation.md , adding information about Kubernetes 1.24.2 to table.
=> Update Installation.md , adding information about Kubernetes 1.24.2 to table.

kubemarine/procedures/check_paas.py
Geo check UI should align with other checks
Keep only three checks, each with the same number
=> [MANOPD-80122] geo-check better ui

kubemarine/core/connections.py
* Sometimes parallel operations using RemoteExecutor fail if [gateway nodes](https://github.com/Netcracker/KubeMarine/blob/0.8.0/documentation/Installation.md#gateway_nodes) are used. This is most probably caused by sharing of the same gateway connection instance.
* Create new instance of gateway connection for each node even if the gateway node is the same.
**TestCase 1**
- OS: Any
Steps:
1. Configure at least two nodes having the same gateway node.
2. Run any procedure.
Results:
| `detect_installed_packages_versions` fails | Procedure is successful |
=> MANOPD-80882 Threads share the same gateway connection instance

kubemarine/resources/configurations/defaults.yaml, kubemarine/thirdparties.py
* Long loading times for target files
* Setting the file upload timer to two minutes
=> Timeout for thirdparty download

documentation/Maintenance.md
* Need to make a note that rollback is not supported. 
None
None
**TestCase 1**
- Hardware: 
- OS: 
- Inventory: 
Steps:
1. 
Results:
|  |  |
=> rollback note

requirements.txt, setup.cfg
Need to revert since causes issues with 4.2.0
Reverts Netcracker/KubeMarine#247
=> [MANOPD-81657] Revert "Bump ansible from 2.9.9 to 4.2.0"

kubemarine/plugins/calico.py
* Deploy Kubernetes fails when `PSP` is enabled
* Implement method that covers `PSP` in `ClusterRoles`
Not applicable
**TestCase 1**
Check if the deployment works
- Hardware: 2CPU/4GB
- OS: Oracle Linux 7
- Inventory: FullHA
Steps:
1. Run installation procedure. The `cluster.yaml` has default settings for `rbac.admission` ans `rbac.psp`
Results:
=> [MANOPD-81799]Deploy Kubernetes failed

kubemarine/resources/configurations/globals.yaml
* added correct pause image versino for kuber 1.25
- Hardware: 
- OS: 
- Inventory: 
Steps:
1. 
Results:
|  |  |
=> Kubernetes 1.25 pause version fix

documentation/Installation.md
Fixed the link to (https://github.com/Netcracker/KubeMarine/blob/main/kubemarine/templates/haproxy.cfg.j2) in Installation.md
=> Fix_link in Installation.md

README.md
* Suggest to check iaas/paas in Running Cluster Installation section.
* Added missed maintenance procedures.
=> MANOPD-81791 README improvements

documentation/Installation.md, documentation/Troubleshooting.md
Adding information about Kubernetes 1.25.2 components to table . And new case to troubleshooting guide.
=> Documentation/table versions&tg

.github/workflows/release.yaml, README.md
*  Need Update document use binary files and remove support build windows binary
* Fix documents
=> Update document use binary files and remove support build windows binary

documentation/Troubleshooting.md
Added issue 'Garbage Collector does not initialize if convert webhook is broken' to Troubleshooting.md
=> [PSUPCLPL-11209] Added issue to Troubleshooting.md

kubemarine/__main__.py
* The need to output the version in binary kubemarine
* Added support for kubemarine version output
=> [MANOPD-82463] Kubemarine --version for binary doesn't work

documentation/Kubecheck.md, kubemarine/apt.py, kubemarine/packages.py, kubemarine/procedures/check_iaas.py, kubemarine/resources/configurations/defaults.yaml, kubemarine/resources/scripts/check_url_availability.py, kubemarine/system.py, kubemarine/yum.py
During check_iaas we don't check packages and their repositories.
Added two tasks:
* `software.packages.repositories` for check repositories availability;
* `software.packages.availability` for check packages availability;
**TestCase 1**
- Hardware: 
- OS: 
- Inventory: 
Steps:
1. Run `check_iaas`
Results:
| No tasks for packages | Two new tasks |
=> [MANOPD-82392] - add check_iaas tasks for check pakages and repos

kubemarine/resources/configurations/defaults.yaml
Reverts Netcracker/KubeMarine#319
to update fix for Ubuntu/CentOS8
=> Revert "[PSUPCLPL-11062] Update defaults.yaml"

documentation/Troubleshooting.md
Please include a summary of the change and describe issue. Please also include relevant motivation and context.
* Doc update
PSUPCLPL-11062
* Doc update
* Manual step 
**TestCase 1**
- Hardware: 
- OS: Centos 
- Inventory: 
Steps:
1. 
Results:
| ------ | …
=> [PSUPCLPL-11062] Update Troubleshooting.md

documentation/Troubleshooting.md
Added a chapter to TG about random 504 error at the cluster ingresses.
PSUPCLPL-11380
Added solution how to check and allow pod2pod traffic in OpenStack IaaS.
-
-
=> [PSUPCLPL-11380] Update TG - add Random 504 Error on Ingresses chapter

requirements.txt, requirements_nt.txt
=> Make paramiko common for Linux and Windows deployers

documentation/Installation.md
This pull request is created after reviewing the changes in installation.md with reference to the following pull request.
https://github.com/Netcracker/KubeMarine/pull/338 
* 
* Manual step 
**TestCase 1**
- Hardware: 
- OS: 
- Inventory: 
Steps:
1. 
Results:
| Before | …
=> Documentation Review and Update

documentation/Installation.md, documentation/Maintenance.md
Need to describe how to use JSON schemas in IDEs.
=> How to use JSON schemas in IDEs

kubemarine/resources/configurations/globals.yaml
Add RHEL8.7 support by using appropriate constant
**TestCase 1**
- Hardware: 
- OS: 
- Inventory: 
Steps:
1. 
Results:
|  |  |
=> Add RHEL8.7 support

.github/workflows/release.yaml
* After #358 `workflows/patch.yaml` stopped working.
* Use softprops/action-gh-release action for create release and upload artifacts.
* Detect target_commitish property of the release that will be used by `workflows/patch.yaml`.
**TestCase 1**
Steps:
1. Release the release that contains patches.
Results:
| Patches are not deleted | Patches are deleted automatically |
=> Fix patch autodeletion workflow

kubemarine/procedures/check_paas.py
* check_paas incorrectly checks ipam configuration of calico plugin in ConfigMap.
* Fixed detection of IP version.
* Fixed detection of changes using DeepDiff.
**TestCase 1**
- Hardware: 
- OS: 
- Inventory: 
Steps:
1. Run default installation.
2. Run `check_paas --tasks calico.config_check`
ER=AR: Success
3. Change `plugins.calico.cni.ipam.(ipv4 or ipv6 depending on what IP version is used)` to the non-default value.
4. Run `check_paas --tasks calico.config_check`
AR: Success
ER: Fail
=> Fix calico configuration check

kubemarine/resources/configurations/defaults.yaml, kubemarine/resources/configurations/globals.yaml, kubemarine/resources/schemas/definitions/services/kubeadm.json, test/unit/test_upgrade.py
globals.yaml updated with new images and SHA
* 
None
None
Only doc update
=> PSUPCLPL-11968 support latest k8s: 1.23,1.24,1.25

documentation/Installation.md
Doc update to extend the list of supported OS versions.
RHEL 8.6, RHEL 8.7 are added.
Not applicable
Not applicable
=> Update IN - add RHEL 8.6, 8.7 to supported OS list

.github/workflows/tests.yaml
* Added [xenon](https://github.com/rubik/xenon) check for cyclomatic complexity (based on [radon](https://github.com/rubik/radon)), if absolute result for all files will be estimated as B or worse.
Radon runs as read-only operation, because xenon prints only problem places without full report.
=> MANOPD-86805 Radon cyclomatic complexity check

documentation/Installation.md, test/unit/test_admission.py, test/unit/test_upgrade.py
Added missed test for default `rbac.admission` value depended on kubernetes version & added information in doc.
=> Default admission test & doc

documentation/Installation.md
* Need to update Installation.md with new information about minimal prerequisites for Deployment Node, because a new version of ansible has been added
* Added information about minimal prerequisites for Deployment Node
=> [MANOPD-1] Update Installation.md about minimal prerequisites for Deployment Node

documentation/Installation.md, documentation/Troubleshooting.md, kubemarine/resources/schemas/definitions/plugins/installation/helm.json
* made doc update
* fixed some md issues
* 
* Manual step 
**TestCase 1**
- Hardware: 
- OS: 
- Inventory: 
Steps:
1. 
Results:
|  |  |
=> Documentation Review

documentation/Installation.md
* It is necessary to update the default version of kubernetes in the documentation
* The default version of kubernetes has been updated in Installation.md
=> Update default version in Installation.md

test/unit/test_migrate_kubemarine.py, test/unit/test_upgrade.py
* Unit tests are failing on Python < 3.9.
* Change `with` statement format to work around https://bugs.python.org/issue12782
=> W/A Python issue 12782 in unit tests.

documentation/Installation.md
=> [MANOPD-88926] DNS_names_can_not_be_resolved-Update Installation.md

kubemarine/core/flow.py, kubemarine/core/schema.py, kubemarine/procedures/do.py
Remote temporary option --ignore-schema-errors.
=> Remove --ignore-schema-errors CLI option

documentation/internal/Patches.md, kubemarine/core/flow.py, kubemarine/procedures/install.py
Added examples how to implement `Action.run()` in patches in common situations.
=> CPDEV-91458 Add examples how to write patches

kubemarine/plugins/__init__.py
Stderr of helm process is absent in debug.log.
Fixes #444
Implement streaming of both helm's stdout and stderr to the logging framework.
**TestCase 1**
1. Configure helm plugin and run `kubemarine install --tasks deploy.plugins`.
Results:
| `dump/debug.log` contains only helm's stdout | `dump/debug.log` contains  both helm's stdout and stderr |
=> [CPDEV-91579] Stream helm output to logging framework

documentation/Installation.md
* An example of using the `config` option has been added to the section dedicated to **loadbalancer**
https://github.com/Netcracker/KubeMarine/issues/128
* Docs updated
=> Need at least small example usage of "config" parameter.

.github/workflows/transfer_repo_image.yaml, ci/Dockerfile-transfer
Added docker image, that contains github bare repo inside.
Pipeline runs every Friday on 0:00 UTC. Also it can be run manually.
=> [CPDEV-92236] - repo image

kubemarine/apparmor.py
* `prepare.system.setup_apparmor` installation fails on Ubuntu 22.04.1 if sssd is preinstalled.
* The reason is in malformed JSON output of AppArmor from 3.0.0 to 3.0.8 in some cases.
https://gitlab.com/apparmor/apparmor/-/issues/295
* Since AppArmor 3.0.9 or later is not available in repositories for Ubuntu 22.04, manually replace incorrect pattern `"processes": {], ` to `"processes": {"`.
**TestCase 1**
1. Install sssd on Ubuntu 22.04.1.
This can be done by `kubemarine install --tasks prepare.dns,prepare.package_manager` and section
```yaml
services
packages:
install:
- sssd
```
2. Run
```
cp /usr/lib/x86_64-linux-gnu/sssd/conf/sssd.conf /etc/sssd/.
sudo chmod 600 /etc/sssd/sssd.conf
sudo systemctl enable sssd
sudo systemctl start sssd
```
3. Run installation
Results: …
=> [CPDEV-90331] Workaround malformed output of apparmor_status --json

documentation/Troubleshooting.md
Various issues with etcd timeout can be solved by tuning etcd parameters.
PSUPCLPL-7074
Doc update only: Troubleshooting guide is update with the case of etcd timeout and recommendations about etcd tuning.
Not applicable
None
=> [PSUPCLPL-7074]Update TG: Add Etcdserver Timeout Issue

documentation/Maintenance.md
* some upgrade best practises and notes added https://github.com/Netcracker/KubeMarine/pull/539/files#diff-64b0849aaaac97283fa79a2e29fed3a951bbbf01918e624f402a8ab297dbb182R209
* fix links to IN
=> [CPREQ-6280] added upgrade recommendation notes

kubemarine/resources/configurations/compatibility/internal/kubernetes_images.yaml, kubemarine/resources/configurations/compatibility/internal/packages.yaml, kubemarine/resources/configurations/compatibility/internal/plugins.yaml, kubemarine/resources/configurations/compatibility/internal/thirdparties.yaml, kubemarine/resources/configurations/compatibility/kubernetes_versions.yaml
* v1.28.3 support has been added
kubemarine install or upgrade
**TestCase 1**
- Hardware: 
- OS: 
- Inventory: 
Steps:
1. 
Results:
|  |  |
=> k8s v1.28.3 support

kubemarine/admission.py, kubemarine/core/connections.py, kubemarine/core/executor.py, kubemarine/core/log.py, kubemarine/core/utils.py, kubemarine/core/yaml_merger.py, kubemarine/demo.py, kubemarine/procedures/check_paas.py, kubemarine/resources/scripts/check_url_availability.py, pyproject.toml
* After `referencing` package version is increased, mypy checks failed.
* Increased dependency on mypy and fix type annotations.
=> Increase mypy dependency

documentation/Kubecheck.md, kubemarine/core/utils.py, kubemarine/kubernetes/__init__.py, kubemarine/plugins/builtin.py, kubemarine/plugins/calico.py, kubemarine/procedures/check_paas.py, kubemarine/resources/schemas/definitions/services/kubeadm.json, scripts/thirdparties/src/software/plugins.py, test/unit/plugins/__init__.py
* Some PaaS checks fail without detailed reason:
* 207 Pods Condition
* 220 Control Plane Configuration Status
* 224 Calico Configuration Check
* Missed some default plugins in some checks:
* 222 Default Services Configuration Status
* 223 Default Services Health Status
* Calico env configuration is not fully checked.
* Added DEBUG logs when comparing configurations to show the difference.
* Added missed plugins and services to the checks.
* Calico env variables for calico-node and calico-typha are compared for absent/extra/changed variables.
**TestCase 1**
Check control plane configuration.
Steps:
1. Install any cluster.
2. Change extraArgs/extraVolumes for services.kubeadm.apiServer or other control plane configuration, or change services.kubeadm.kubernetesVersion in the `cluster.yaml`. …
=> [CPDEV-94448] Improve check_paas checks and logging

documentation/Installation.md, kubemarine/resources/configurations/globals.yaml
Updated golbals.yaml to add rhel_8.9 version in the supported os family.
* 
Add RHEL 8.9 family
* 
**TestCase 1**
- OS: rhel_8.9
- K8s Version - v1.23.6
Steps:
Kubemarine check_iaas
AR: Check_iaas suceeded
Kubemarine install
AR: Installation suceeded
Kubemarine check_pass
AR: check_pass suceeded
=> [CPREQ-8282]-Certify_Kubemarine_for_RHEL_8.9

kubemarine/core/defaults.py, kubemarine/core/utils.py, kubemarine/cri/containerd.py, kubemarine/modprobe.py, kubemarine/plugins/calico.py, kubemarine/resources/schemas/definitions/services/sysctl.json, kubemarine/sysctl.py, kubemarine/system.py, test/unit/test_defaults.py
* Implement unified process to manage primitive values represented as strings
* `defaults.manage_primitive_values()` accepts list of sections to process and convert primitive values.
test_defaults.py - cover algorithm in  `default.manage_primitive_values()`
=> [CPDEV-82348] Manage primitive values represented as strings

kubemarine/procedures/upgrade.py
Reverts Netcracker/KubeMarine#582
=> Revert "[CPDEV-96588] - apply kubeadm-config during upgrade"

scripts/thirdparties/src/software/plugins.py
* Remove temporary workaround in thirdparties sync tool.
=> Remove temporary workaround in thirdparties sync tool

documentation/Installation.md, documentation/LoadBalancing.md
It is required to describe how maintenance mode is currently supported in KubeMarine
* Updated doc `LoadBalancing.md` with a separate topic about maintenance mode
* Added links to this topic from configuration sections in `Installation.md`
=> Maintenance mode support details

documentation/Installation.md, documentation/Troubleshooting.md
Several topics were added in Installation and Troubleshooting guides:
- information about necessary protocols (IPIP and VRRP) in Installation notes in part of requirements
- information about disabled GARP protocol and how to detect the problem
=> [PSUPCLPL-14328] Add new topics about VRRP, GARP and IPIP

kubemarine/core/log.py
* Fix incorrect source method in dump/debug.log for python >= 3.11
* Added switch of behavior in `log.caller_info()` and `EnhancedLogger.verbose()` to adapt to python >= 3.11
**TestCase 1**
Steps:
1. Install cluster using Kubemarine on python >= 3.11 (for example, using docker image)
2. Check dump/debug.log
Results:
| Logs contain records with source method `log.caller_info` and `log.verbose` | The same records contain real source methods |
=> Fix logging for python >= 3.11

kubemarine/patches/__init__.py
This PR is for fixing the missing path from PR #555
=> Fix Missing Patch

documentation/Installation.md, documentation/LoadBalancing.md
Please include a summary of the change and describe issue. Please also include relevant motivation and context.
* 
* 
* Manual step 
**TestCase 1**
- Hardware: 
- OS: 
- Inventory: 
Steps:
1. 
Results:
|  |  |
Indicate new or changed …
=> Doc Review relating to https://github.com/Netcracker/KubeMarine/pull/596

documentation/Troubleshooting.md
* In some cases `audit` daemon could affect Kubernetes cluster node functioning.
* Update troubleshooting guide
Not applicable
=> [PSUPCLPL-14914] TG update

documentation/Kubecheck.md
* Some statements should be covered in `Kubecheck` documentation
* Update documentation
=> Kubecheck doc update

.github/workflows/ci.yaml, .github/workflows/tests.yaml, Dockerfile, kubemarine/core/cluster.py, kubemarine/core/schema.py, kubemarine/core/static.py, kubemarine/core/utils.py, kubemarine/packages.py, kubemarine/procedures/__init__.py, kubemarine/procedures/backup.py, kubemarine/resources/scripts/source/ipip_check/go.mod, pyproject.toml, requirements-pyinstaller.txt, scripts/ci/build_binary.py, scripts/ci/custom-hooks/hook-cryptography.py, scripts/ci/install_package.py, test/unit/plugins/test_inventory.py
* Drop support python 3.7
* Code changes to respect minimal version of python 3.8
* Update helm v3.14.4
* Added dependency on useful-types.
* Updated python dependencies
* Updated ansible to 7.7.0
* Fixes in schema.py to support new jsonschema version.
* Updated go version for ipip_check.
Changed tests to respect changed JSON schema validation errors.
=> [CPDEV-101744] Update helm, python dependencies

pyproject.toml, test/unit/plugins/test_nginx_ingress.py
https://github.com/Netcracker/KubeMarine/actions/runs/10524929312/job/29162682620
* rework versioning  
none
=> reworked version check algoritm to packaging.pypa.io

documentation/Kubecheck.md
Add minor changes to heading in [Kubecheck.md](https://github.com/Netcracker/KubeMarine/blob/network_sub-chapter/documentation/Kubecheck.md)
=> [CPDEV-95454] Make network sub-chapter clickable

documentation/Installation.md, kubemarine/resources/configurations/globals.yaml
Added rocky linux 9.4 to the supported version and check the functionality.
* 
**TestCase 1**
- OS: Rocky linux 9.4
- Inventory: All in one
Steps:
1. kubemarine install 
Results:
| Not supported | Successful |
2. kubemarine upgrade
Results:
| Not supported | Successful |
**TestCase 1**
- OS: Rocky linux 9.4
- Inventory: Miniha
Steps:
1. kubemarine install 
Results:
| Not supported | Successful |
2. kubemarine upgrade
Results:
| …
=> [PSUPCLPL-16761] rockylinux 9.4 support

kubemarine/resources/configurations/globals.yaml
Versions were updated according to request from related issue.
https://github.com/Netcracker/KubeMarine/issues/693
=> RHEL 8.10, 9.3 9.4 support added

documentation/Troubleshooting.md
It's necessary to unify TG based on the template provided in the epic
=>  [CPDEV-107029] Update TroubleshootingGuide.md according to unified Cloud Infra TG requirements

.github/pull_request_template.md, README.md, documentation/internal/Release.md
Need to add missing information useful for newcomers
* Added internal document with instruction how to make release
* Added links to internal documents in readme
* Described repository structure
* Added patches to PR checklist
=> [CPREQ-10101] Add newcomer docs

documentation/Installation.md, kubemarine/resources/configurations/globals.yaml
Added rocky linux 9.5 to the supported version and check the functionality.
* 
**TestCase 1**
- Hardware: 
- OS: Rocky linux 9.5
- Inventory: Miniha
Steps:
1. Kubemarine install
Results:
| Not supported | Successful |
2. Kubemarine upgrade
Results:
| Not supported | Successful |
=> [PSUPCLPL-17308]-rockylinux 9.5 support 

kubemarine/kubernetes/__init__.py
On Kubernetes upgrade, if containerd is upgraded from 1.6 to 1.7 on Ubuntu 20.04 or 22.04, host network pods (e.g. nginx) become unavailable with following error (if LB is present):
```
curl: (35) error:0A000126:SSL routines::unexpected eof while reading
```
This happens, because after containerd upgrade, containerd fails to cleanup pod sandboxes from previous containerd version, particularly it leaves iptables rules in incorrect state.
Changed containerd upgrade procedure.
Before it was:
1. upgrade containerd
2. delete containers from previous containerd version
Now it becomes:
1. stop kubelet
2. delete pod sandboxes (in two steps to support AIO)
3. upgrade containerd
4. start kubelet
This way we make sure that pod sandboxes and containers are deleted BEFORE upgrade, not after. …
=> containerd upgrade breaks hostPort pods

kubemarine/plugins/calico.py
Calico v3.30.3 has an issue with missing calico-apiserver permissions
* Implemented WA to patch calico-apiserver v3.30.3 manifest before applying - adding required permissions for staged network policies
* For permanent fix created issue in calico https://github.com/projectcalico/calico/issues/11017
=> fix calico-apiserver permissions
